### ISSUE TITLE
Reported Broken Resolvers

### ISSUE THREAD

**Issue by tknorris** [tknorris/script.module.urlresolver#1]
Hi sir,right now these hosts all cannot be resolved: gorillavid.in,movdivx.com,putlocker.com,sockshare.com,thevideo.me,tubemotion.com,uploadc.com.

**Comment by tknorris** [comment]
putlocker and sockshare have been offline for over a year

**Comment by tknorris** [comment]
gorillavid tested and working

**Comment by brmnh** [comment]
sorry,I made a few mistake.

**Comment by tknorris** [comment]
no worries, some of them are broken. I'll push fixes later today.

**Comment by tknorris** [comment]
movdivx fix pushed

**Comment by brmnh** [comment]
thank you sir

**Comment by tknorris** [comment]
tubemotion doesn't have a resolver and I just pushed a fix for uploadc

**Comment by brmnh** [comment]
sir you are so quick

**Comment by brmnh** [comment]
hi sir,sorry to disturb you again.When I play the video from the host veeHD.com,some video can be played,some cannot be.When the video from veeHD.com cannot be played,the kodi log file is like this:
14:07:24 T:1972786072  NOTICE: 1Channel: Attempting to play url: http://veehd.com/video/4720747_The-Saints-Double-Trouble--1940-Ultimate-Classics-Collection
14:07:49 T:1972786072  NOTICE: URLResolver: Stream UrlOpen Failed: Url: http://v211.veehd.com/dl/8d9914a21b0f87c92eb3c5a2d7244f7c/1433160440/6.4720747.avi HTTP Code: 601.
I donot know whst is the problem,Can you fix it?Thanks sir.

**Comment by brmnh** [comment]
I use an external player to play the video,the MX Player Pro.
