### ISSUE TITLE
Openload issue (HotLink)

### ISSUE THREAD

**Issue by Kolifanes** [tknorris/script.module.urlresolver#102]
From yesterday Openload give always error about a Hotlink from website.

**Comment by tknorris** [comment]
Yep, PR's welcome. No one has had time to look at it yet.

**Comment by Kolifanes** [comment]
Do you have test this commit?
`https://github.com/tknorris/script.module.urlresolver/commit/022cb0c01df5ca0e66bc1a9b54f78022cd0cc2a3`

Is give always to me an error, now when i try a OpenLoad Mirror

**Comment by tknorris** [comment]
Working fine here.

**Comment by tknorris** [comment]
As of 30 minutes ago
