### ISSUE TITLE
OpenLoad again

### ISSUE THREAD

**Issue by Kolifanes** [tknorris/script.module.urlresolver#104]
But we have already the fix based on the addon of Pelisacarta for Italian User

https://github.com/Zanzibar82/plugin.video.streamondemand/commit/e175e701872fc2eb1697ba1e5b432939dcf8e757

**Comment by tknorris** [comment]
If you can adapt the fix to urlresolver, PR's welcome

**Comment by tknorris** [comment]
fix committed, will be in 3.0.13
