### ISSUE TITLE
Vidup & Vidup

### ISSUE THREAD

**Issue by azzy9** [tknorris/script.module.urlresolver#109]
Hi,
I first want to say how I appreciate all the work done on here,
it is awesome how easy it has been made to resolve links.

So for the issue:

Vidup.org and vidup.me are different hosts for videos.
as such their code for veiwing videos is different.
vidup.me uses the JS packer function.
vidup.org just puts the link in the javascript, so just requires a
regular expression to search for the link.
For this reason I split up the plugins.

They have been joined together again and is giving me an error while trying to resolve the link for vidup.org.

I could just make another pull request but was just wondering if there was a reason they were put back together and plus I do not want to annoy people by making needless pull requests. 

Link examples if needed (Just replace ??? with id):

Link URL: http://beta.vidup.me/embed-???.html
ID: 0gpadjsp828d

Link URL: http://vidup.org/embed.php?file=???
ID: 7014c864

**Comment by tknorris** [comment]
Do you have a vidup.org link? We merged them because we couldn't find any vidup.org links

**Comment by tknorris** [comment]
I see you put one in your post. If you re-PR it, I'll add it back in the next build.

**Comment by azzy9** [comment]
Thanks, I will make a PR soon.  :+1:
vidup.org is mainly used for anime, so that is most probably why you don't see many links.
