### ISSUE TITLE
Problem in processCaptcha?

### ISSUE THREAD

**Issue by Viper2k4** [tknorris/script.module.urlresolver#114]
Hi,

is there actual a problem with processCaptcha? I use the function since months. But now (one or two weeks). It throw a exception HTTPError 400. I debug it a bit and this happens direkt here:

https://github.com/tknorris/script.module.urlresolver/blob/master/lib/urlresolver/plugins/lib/recaptcha_v2.py#L135

Is this a problem of the API or does simply the SiteKey dont support the Fallback?

Greetings

**Comment by tknorris** [comment]
Sites can disable the fallback. If you are getting a 400 it probably means they have.

**Comment by Viper2k4** [comment]
What a fast response :)

Sad but Thanks
