### ISSUE TITLE
thevideobee.to broken, unable to fix it

### ISSUE THREAD

**Issue by Gujal00** [tknorris/script.module.urlresolver#117]
It looks like slowly sites have started enforcing HTTPS with TLS1.2 and "thevideobee.to" have followed suit
The t0mm0.common included with SMU cannot do TLS1.2 and hence unable to open the page
I have played around with "script.module.pyopenssl" by  Andrew Leech (https://github.com/andrewleech/) in opening TLS1.2 using script.module.requests and have been successful but unfortunately it does not come with android support, it only comes with MacOS, Windows and Linux_x86_x64 support
The developer says he is not looking at pyopenssl anymore and suggests pycurl+human_curl instead, which I have been unable to get working on Windows.
Can you please help by
Either repackaging pycurl+human_curl to work with all the platforms for which packages included in it
OR
improve script.module.pyopenssl to support Android ARM as well. We can then easily write SMU plugins to those sneaky TLS1.2 sites.

Thanks
Example link: https://thevideobee.to/aoosdpepaipf.html

**Comment by tknorris** [comment]
You won't need to do all this. Krypton comes with Python 2.7.11 which supports TLS. So, for now, just accept that these https links won't work until Krypton comes out.

**Comment by Gujal00** [comment]
Agreed, will wait for Krypton release.
Thanks
