### ISSUE TITLE
Hi Sir,these resolvers seem donot work now

### ISSUE THREAD

**Issue by brmnh** [tknorris/script.module.urlresolver#12]
nosvideo.com      noslocker.com     thefile.me

**Comment by tknorris** [comment]
I'll take a loo at them.

**Comment by tknorris** [comment]
nosvideo is offline according to their website.

**Comment by tknorris** [comment]
fix for thefile.me submitted. I'll push 2.9.5 soon with the fix as well.

**Comment by brmnh** [comment]
thanks sir.

**Comment by brmnh** [comment]
Sir,the resolver thefile.me seems still not working.

**Comment by tknorris** [comment]
Did you download the one from my github?

**Comment by brmnh** [comment]
Yes,I did.

**Comment by tknorris** [comment]
Hmm, odd because it's working fine for me.

**Comment by tknorris** [comment]
Yep, just tested it again and it's working fine.

**Comment by brmnh** [comment]
Sir,can you give an example that worked ?I will try it.Thanks.

**Comment by tknorris** [comment]
I don't want to post that here, but go to primewire.ag do an advanced search and enter thefile.me as the "Hosted At" value. I've tried several and they all worked.

**Comment by brmnh** [comment]
I will try.

**Comment by brmnh** [comment]
I tried several videos,some works,some doesnot.I seems not to be the resolver's problem.
