### ISSUE TITLE
Hi Sir,the resolver openload.co  seems not work

### ISSUE THREAD

**Issue by brmnh** [tknorris/script.module.urlresolver#121]
i check the site in browser,it has no problem.

**Comment by brmnh** [comment]
are you online,Sir?

**Comment by tknorris** [comment]
I'm sure someone will check it eventually.

**Comment by sraedler** [comment]
I tried a bi...

`part = re.findall('sub\\\/(.*)~"', html)`
`url = "https://" + "openload.io/stream/" + media_id + "~" + part[0] + "?mime=true"
` 
I could build the right url, but I always get "wrong ip" error...

**Comment by tknorris** [comment]
fixed in 3.0.16 just pushed
