### ISSUE TITLE
flashx.tv uses cloudflare

### ISSUE THREAD

**Issue by sraedler** [tknorris/script.module.urlresolver#122]
hey,
flashx now using cloudflare, can you pass it?

I tried a bit, sometimes I can get the url by changing the regex for the stream to `file\s*:\s*"(http.*?)"[^"]label`

But the cloudflare problem is there.

**Comment by tknorris** [comment]
I'll take a look when I get a chance.

**Comment by tknorris** [comment]
I'm closing this issue as flashx still doesn't work from the website.

**Comment by sraedler** [comment]
For me it's working from website, I just have to click multiple on process button...

**Comment by tknorris** [comment]
I can try it again. I get to the point for the video to play but it just spins and spins on the website.
