### ISSUE TITLE
Hi Sir,the resolver openload.co seems broken again

### ISSUE THREAD

**Issue by brmnh** [tknorris/script.module.urlresolver#126]
can  you fix it?thanks very  much.

**Comment by tknorris** [comment]
I'm sure someone will look at it when they have time.

**Comment by brmnh** [comment]
Sir are you online?Can you fix yorself?Thanks very much.

**Comment by boogiekodi** [comment]
change numbers.js to n.js

**Comment by brmnh** [comment]
Sir，which number？where？

**Comment by brmnh** [comment]
are you online?

**Comment by boogiekodi** [comment]
in https://offshoregit.com/tvaresolvers/ol_gmu.py

tk made it remote, unless you can modify your url resolver to work with the copy of that file locally, you can modify the line 88 in it to point n.js instead of numbers.js

**Comment by tknorris** [comment]
I'll fix it now and upload a new one.

**Comment by brmnh** [comment]
thanks SIr

**Comment by tknorris** [comment]
Uploaded, it'll show up once the cached on OSG expires.

**Comment by brmnh** [comment]
Sir I download and install  the  zip  you  upload,but  the. resolver  still  not. work.

**Comment by brmnh** [comment]
Sorry.,it works now.
