### ISSUE TITLE
HI Sir the resolver thevideo.me seems broken

### ISSUE THREAD

**Issue by brmnh** [tknorris/script.module.urlresolver#135]

**Comment by tknorris** [comment]
Yes, they broke it again. I committed a fix earlier today.

**Comment by brmnh** [comment]
Sir,your fix does not work now.

**Comment by alifrezser** [comment]
I committed the fix #134

**Comment by brmnh** [comment]
Sir，still not  work

**Comment by tknorris** [comment]
You don't need to keep telling me. If I haven't closed the issue, then I know it doesn't work. The host is actively trying to prevent scraping so be prepared for it to not work frequently until they realize it's pointless and give up.
