### ISSUE TITLE
Hi Sir,the resolver openload.co seems not work again

### ISSUE THREAD

**Issue by brmnh** [tknorris/script.module.urlresolver#143]

**Comment by brmnh** [comment]
the resolver nowvideo.sx not working either

**Comment by tknorris** [comment]
thanks, I'm sure someone will look at them when they have time

**Comment by tknorris** [comment]
(FYI, OpenLoad is still working fine for me)

**Comment by tknorris** [comment]
Status:
openload - Working
nowvideo.sx - Working
neodrive.co
idowatch.net
vshare.eu
flashx.tv
uptobox.com
wholecloud.net
userscloud.com
vidgg.to

**Comment by xsteal** [comment]
OpenLoad resolve, http://pastebin.com/mRb3qt3A
