### ISSUE TITLE
Hi Sir,openload.co may work in some movie

### ISSUE THREAD

**Issue by brmnh** [tknorris/script.module.urlresolver#145]
but in the others it doesnot work,for example the  movie"death on the nile".

**Comment by tknorris** [comment]
allthe ones I've tested worked fine.

**Comment by brmnh** [comment]
no encoded section found,it says

**Comment by tknorris** [comment]
I need a link

**Comment by brmnh** [comment]
Sir,can you try "death on the nile"?thanks.

**Comment by tknorris** [comment]
I need a link, there could be hundreds of instance of that movie on their site and I have no way to find it even if there was

**Comment by brmnh** [comment]
Hi Sir,the link is http://www.alluc.ee/l/Death-on-the-Nile-1978-720p-BluRay-x264-YIFY-mp4/8hxkpej0

**Comment by tknorris** [comment]
Thanks, I'll check it out

**Comment by tknorris** [comment]
It worked fine here. You might have an out of date ol_gmu. Give it time to update.
