### ISSUE TITLE
Hi Sir,can you make some change to openload.co resolver

### ISSUE THREAD

**Issue by brmnh** [tknorris/script.module.urlresolver#152]
so that do not need the ip pair process?also the resolver thevideo.me.Thanks very much.

**Comment by tknorris** [comment]
No, it has been made that way on purpose. Follow the directions if you want to watch those streams.

**Comment by linbert** [comment]
What are the directions??

**Comment by tknorris** [comment]
Do what the window says to do.

**Comment by linbert** [comment]
Mh ok, I just get an Error that url cannot be resolved.

**Comment by tknorris** [comment]
It sounds like you aren't typing the correct url. What url did you type?

**Comment by linbert** [comment]
I am using it over bs to app. There it says url cannot be resolved. I couldnt see the url in the logs

**Comment by tknorris** [comment]
I don't understand what you are saying
