### ISSUE TITLE
rapidvideo com off ?  

### ISSUE THREAD

**Issue by firerm** [tknorris/script.module.urlresolver#153]
RapidVideo is not playing anymore ...can anyone confirm that ?

**Comment by tknorris** [comment]
I'll check it. (Also, please don't post links to videos here)

**Comment by tknorris** [comment]
The CDN server is having certificate issues:
12:24:31 T:140089014974208 WARNING: URLResolver: Stream UrlOpen Failed: Url: https://www162.playercdn.net/xxx|Referer=https%3A%2F%2Fwww.rapidvideo.com%2Fembed%xx&User-Agent=Mozilla%2F5.0+%28Windows+NT+6.3%3B+rv%3A36.0%29+Gecko%2F20100101+Firefox%2F36.0 HTTP Code: 600 Msg: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590) (ENCODED)

You can make them work by disabling certificate validation as described [here](https://github.com/tknorris/tknorris-beta-repo/issues/45), but I don't recommend it.
