### ISSUE TITLE
Google Drive not working anymore

### ISSUE THREAD

**Issue by Kolifanes** [tknorris/script.module.urlresolver#159]
Hi,

Google has changed the domain to https://drive.google.com/ can you add the support to URLResolver?
Thanks

**Comment by tknorris** [comment]
I can look at it when I get time. Do you have a link I can test with?

**Comment by Kolifanes** [comment]
Yes, https://drive.google.com/file/d/0BxZRYVcK8FTVQU1tZk5aMm5uX2s
Thanks

**Comment by tknorris** [comment]
Thanks, I'll try it when I get time.

**Comment by Kolifanes** [comment]
If this can help, you can take a hint from streamondemand here is working
https://github.com/streamondemand/plugin.video.streamondemand/blob/master/servers/googledrive.py

**Comment by tknorris** [comment]
Thanks. I also have my own code from SALTS that parses google drive links.

**Comment by tknorris** [comment]
fixed in #165
