### ISSUE TITLE
Hi Sir,the resolver vidzi.tv seems doesnot work now

### ISSUE THREAD

**Issue by brmnh** [tknorris/script.module.urlresolver#16]

**Comment by brmnh** [comment]
and these resolvers uploadc.com   vidlockers.ag   neodrive.co   cloudtime.to    nowvideo.sx    nosvideo.me    noslocker.com  seem also broken.

**Comment by tknorris** [comment]
vidzi.tv - tested, working
uploadc.com - fixed regex
vidlockers.ag - no resolver exists - I'll look at adding one.
neodrive.co - tested, working
cloudtime.to - tested, working
nowvideo.sx - fixed
nosvideo.me - fixed
noslocker.com - fixed

**Comment by brmnh** [comment]
Thanks Sir.
