### ISSUE TITLE
DailyMotion Resolever not working 

### ISSUE THREAD

**Issue by firerm** [tknorris/script.module.urlresolver#173]
Can anyone confirm that dailymotion not working ?

**Comment by tknorris** [comment]
Yep, it's already fixed on github. The fix will be released in 3.0.23

**Comment by firerm** [comment]
I reopen this beacause the actual Dailymotion Fix is not working (I Know that is not pushed yet) but I tried to replace the dailymotion.py and not working to my end.

Any Progress News ?

**Comment by tknorris** [comment]
I don't normally use DailyMotion and Lambda submitted the fix. I'll ask him about it.

**Comment by firerm** [comment]
Thanks , I hope Lambda do his magic because I had I upload many documantaries in dailymotion :+1:

**Comment by firerm** [comment]
Thanks It will be awesome to fix this because it have upload many
documantaries in dailymotion...

I hope Lambda do his magic :)

Στις Τετ, 26 Οκτ 2016 - 15:56 ο χρήστης tknorris <notifications@github.com>
έγραψε:

**Comment by alifrezser** [comment]
Already pushed a fix #181
