### ISSUE TITLE
wholecloud

### ISSUE THREAD

**Issue by Viper2k4** [tknorris/script.module.urlresolver#185]
Heho,

i take a look at the moveshare.py. And it seems like there is a check for differnet cases. And the API-Code looks a bit differnt then the one is used on the page. So i dont wanna break the old one and open an Issue :)

Greetings

**Comment by tknorris** [comment]
if they've made changes, you can break wholecloud out into a new resolver

**Comment by tknorris** [comment]
I'm updating the resolver now, will push in a sec.

**Comment by tknorris** [comment]
pushed
