### ISSUE TITLE
some veeHD videos connot be played

### ISSUE THREAD

**Issue by brmnh** [tknorris/script.module.urlresolver#2]
hi sir,sorry to disturb you again.When I play the video from the host veeHD.com,some video can be played,some cannot be.When the video from veeHD.com cannot be played,the kodi log file is like this:
14:07:24 T:1972786072 NOTICE: 1Channel: Attempting to play url: http://veehd.com/video/4720747_The-Saints-Double-Trouble--1940-Ultimate-Classics-Collection
14:07:49 T:1972786072 NOTICE: URLResolver: Stream UrlOpen Failed: Url: http://v211.veehd.com/dl/8d9914a21b0f87c92eb3c5a2d7244f7c/1433160440/6.4720747.avi HTTP Code: 601.
I donot know whst is the problem,Can you fix it?Thanks sir.

**Comment by brmnh** [comment]
I use an external player to play the video,the MX Player Pro.

**Comment by tknorris** [comment]
VeeHD has different ways of handling their videos. Some simply won't work. In this case, veehd refuses to allow that video to be downloaded.

**Comment by brmnh** [comment]
sir can you try this film: the saints double touble

**Comment by tknorris** [comment]
It actually worked fine for me.

**Comment by brmnh** [comment]
I"ll try once more
