### ISSUE TITLE
Hi Sir,I am using project free tv,I met a problem

### ISSUE THREAD

**Issue by brmnh** [tknorris/script.module.urlresolver#20]
when I click tv shows>>last 24 hours,the sign in the corner says error.

**Comment by brmnh** [comment]
This is the log link:http://xbmclogs.com/pjzgbgnbf

**Comment by tknorris** [comment]
projectfreetv went offline. The addon no longer works. Also, it's not part of urlresolver anyway, so this really shouldn't go here.

**Comment by brmnh** [comment]
Oh,sorry Sir.

**Comment by tknorris** [comment]
No worries, just FYI.
