### ISSUE TITLE
get_hidden and SUBMIT (and some other small stuff)

### ISSUE THREAD

**Issue by Viper2k4** [tknorris/script.module.urlresolver#215]
Hi,

what do u think about extending get_hidden? I see so many plugins that use get_hidden to get the hiddenvalues and direct after that they add the submit value to the array.

Should we add an option like "include_submit = false" (i think false is even better for backward compatibility) or build it in an other way? Because i think it would shorten many plugins by one line ^^ and it would be a bit more dynamic.

grettings

*EDIT*

Oh btw. what do u think about an "get_unpacked_data(html)"?

Because many plugins also use a function like this:

```
for match in re.finditer('(eval\(function.*?)</script>', html, re.DOTALL):
        html += jsunpack.unpack(match.group(1))
html = html.replace('\\', '')
```
(xvidstage.py as example)

this could be reduce to:

`html += get_unpacked_data(html)`

I could add it. But i would like to ask before i do it ^^

**Comment by tknorris** [comment]
yeah, they both sound like good ideas. If I can I'll spend some time on them today.

**Comment by tknorris** [comment]
Both methods added and used in all relevant resolvers. Thanks for the suggestion.
