### ISSUE TITLE
Hi Sir,these resolvers seem also broken

### ISSUE THREAD

**Issue by brmnh** [tknorris/script.module.urlresolver#22]
cloudyvideos.com    movreel.com      nosvideo.com     flashx.tv    youwatch.org   180upload.com    vidbux.com     daclips.in     gorillavid.in     movdivx.com     movpod.in

**Comment by tknorris** [comment]
I haven't checked the others yet, but movreel has a notice on their site that they are shutting down. Please check links for each one of these sites and make sure they work in a browser first before I check them.

**Comment by brmnh** [comment]
Hi Sir,I just checked,vibux.com also shuts down,other sites work in browser.

**Comment by brmnh** [comment]
Also resolver vidplay.net doesnot work.

**Comment by tknorris** [comment]
cloudyvideo.com - links seem broken; pages are there, but videos don't work
movreel - site shutdown
nosvideo - fixed
flashx.tv - fixed
youwatch - looks to be a PITA the fix. check it later.
180upload - works for me
vidbux - site shutdown
daclips.in - works for me
gorillavid.in - works for me
movdivx.com - works for me
movpod.in - works for me
vidplay.net - No active links found

**Comment by brmnh** [comment]
Thanks Sir.
