### ISSUE TITLE
helpers.py - remove comments from html

### ISSUE THREAD

**Issue by mrknow** [tknorris/script.module.urlresolver#220]
def get_hidden(html, form_id=None, index=None, include_submit=True):
    hidden = {}

    # remove comments
    r = re.compile('<!--.*?(?!//)--!*>', re.IGNORECASE + re.DOTALL + re.MULTILINE)
    m = r.findall(html)
    if m:
        for comment in m:
            html = html.replace(comment, '')
    if form_id:

**Comment by tknorris** [comment]
Good Idea, I'll add a commit to do that in a bit

**Comment by tknorris** [comment]
added in https://github.com/tknorris/script.module.urlresolver/commit/b5cdad1ccbca9b2e3aca2e5bf45ba079b9330b79
