### ISSUE TITLE
Hi Sir,the resolver letwatch.us seems broken

### ISSUE THREAD

**Issue by brmnh** [tknorris/script.module.urlresolver#23]

**Comment by tknorris** [comment]
the whole site is broken. None of the videos I tested worked in the browser. Please check that before reporting issues. If the video doesn't play in the browser then it won't play in Kodi. You have to check more than just the site is up, you have to make sure that the video actually plays. In this case, all the letwatch.us videos failed.

**Comment by brmnh** [comment]
Sorry Sir.
