### ISSUE TITLE
with premiumize Account openload links not working

### ISSUE THREAD

**Issue by humiboy** [tknorris/script.module.urlresolver#233]
Hello,

I have a premiumize account configure in the url resolver settings. When I will use openload links in Kodi i become the message to pair my ip adress. 

But premiumize supportet openload links. Why i become the message to pair my ip adress? 
Have you a idea to fix this?

**Comment by tknorris** [comment]
If you have the resolver properly configured it should work on openload links that use the /f/ url variant, but not on the ones that have the /embed/ url variant. Premiumize needs to add the /embed/ variant to their validation for those ot be picked up. I'll contact them about that.

Turn on debug and try a openload link and post a log of it.

**Comment by humiboy** [comment]
Thank you tknorris for your answer and help to fix this. I am anderstand and we are waiting for a fix from premiumize.

**Comment by tknorris** [comment]
Well, maybe. Some openload links should work already. They just replied that they will fix the /embed/ issue later today. Do some openload links work for you or none?

**Comment by humiboy** [comment]
Hi,

yes some addons with openload links works by me with no problems. Other addons with openload links i become the pair message.

**Comment by Viper2k4** [comment]
Its a bit funny it seems like they add it internally but they dont add it to the hosterlist. So actual only [valid_url](https://github.com/tknorris/script.module.urlresolver/blob/master/lib/urlresolver/plugins/premiumize_me.py#L79) fails.

With a quick and dirty:

```
if 'openload.' in url:
   url = url.replace('/embed/', '/f/')
```

its work just fine. So it seems like we need to contact them again ^^

**Comment by tknorris** [comment]
I'll let them know.

**Comment by tknorris** [comment]
It looks like their regex has been updated now. The regex is cached in urlresolver for 8 hours, but once that expires the /embed/ links should be handled properly now.
