### ISSUE TITLE
with premiumize Account FlashX links not working

### ISSUE THREAD

**Issue by humiboy** [tknorris/script.module.urlresolver#236]
Hi,

thx again for fix the other Problem with Premiumize and openload Streams.

I have a another problem. Premiumize supports FlashX but this Hoster not working with Premiumize in Kodi.

Can premiumize fix this problem too?

**Comment by tknorris** [comment]
You should probably work that through premiumize support. It's not really a urlresolver problem.

**Comment by humiboy** [comment]
Hi, 

FlashX Stream links with URL Revolver not works but FlashX Links in Exodus Addon works.

**Comment by tknorris** [comment]
Exodus uses urlresolver. So, if it works for one it works for both.

**Comment by humiboy** [comment]
When ist will use the Addon Xstream and the Site Burning Series with FlashX Hoster no Stream works. 

When i use Exodus and my Premiumize creditential in the Addon configured ist Canon See FlashX with Premiumize. 

Ich don't no why with other Addon not works FlashX

**Comment by tknorris** [comment]
Turn on debug and post a log.

**Comment by humiboy** [comment]
Hi

here is  a log.  openload links works with no problem but FlashX not works. 

[kodi.txt](https://github.com/tknorris/script.module.urlresolver/files/637251/kodi.txt)

**Comment by tknorris** [comment]
OK, so there are two things going on here.
1) It looks like premiumize has several url validation regexes that I think are wrong. All of them seem to have the same problem where they contain \\? (which translates to "require a question mark") when what I really think they mean to do is /? (which translates to "an optional forward slash). I'll email them to find out what their intent is and update the resolver if necessary.
2) For some reason the flashx resolver isn't working for you. You are using the latest code that I've released for the flashx resolver and it works for me, but not for you for some reason. @viper2k4 can check to see if my latest fx_gmu.py code works for you?

**Comment by Viper2k4** [comment]
Heho,

FlashX is working just fine for me. 
(Kodi 17, Windows10 and Kodi 17 FireTV)

**Comment by tknorris** [comment]
@viper2k4 thanks for checking. I deleted you comment just in case prying eyes are watching

**Comment by humiboy** [comment]
Hi tknorris

Have you any news from premiumize Support to fix the FlashX  Hoster?

**Comment by tknorris** [comment]
It should be working now. It was the last time I checked.

**Comment by humiboy** [comment]
With Kodi 16 or Kodi 17 you have checked?

**Comment by tknorris** [comment]
I only checked on 17, but in this case it shouldn't matter. You can post a log w/ debug on if oyu want me to look at it.

**Comment by humiboy** [comment]
With Kodi 16 or SPMC and FlashX Stream comes a stream with Dateline Spam...
When i upgrade Kodi 16 to Kodi 17 FlashX works with no Premiumize Account login with no problem.

The problem is Kodi 16 or SPMC?

**Comment by tknorris** [comment]
I don't know what you mean by Dateline Spam. Regardless, if you want me to look at the problem I need a log.

**Comment by humiboy** [comment]
Here is a SPMC Log from my FireTV 4K. When i use FlashX Hoster there not come the right Stream. There come the Spamlink

**Comment by humiboy** [comment]
[spmc.txt](https://github.com/tknorris/script.module.urlresolver/files/688400/spmc.txt)

**Comment by tknorris** [comment]
The problem is Premiumize is not finding the link from flashx and urlresolver is falling back to the flashx resolver which seems not to work on Jarvis. I'm not sure why premiumize can't find the link, but it's not a urlresolver problem:

`21:41:59.138 T:18446744072324604456   ERROR: URLResolver: ResolverError Error - From: Premiumize.me Link: https://www.flashx.tv/embed-1uudoc3ihymc.html: Link Not Found: Error Code: 400`

**Comment by humiboy** [comment]
Thx for the answer. And what can i do to watch FlashX again with Jarvis? Problem is by Premiumize. But why with Kodi 17 FlashX works with no Premium Account?

**Comment by tknorris** [comment]
the flashx resovler works on Krypton but not Jarvis. I'm not really sure why. I don't have a Jarvis test system any more.

**Comment by humiboy** [comment]
Ok i understand. When i watch FlashX Streams i must use Kodi 17. Kodi 16/SPMC have a problem with FlashX.
