### ISSUE TITLE
once again: premiumize.me and urlresolver

### ISSUE THREAD

**Issue by saustark** [tknorris/script.module.urlresolver#238]
hi,
first of all i know this matter is not new, and i read the closed issues regarding premiumize.me carefully.
I have the problem that my premiumize.me account seems not to be recognized by the urlresolver at all.
The result is that i cannot stream any sources via premiumize (from hosters covered by premiumize) when using addons based on urlresolver.

I have exactly the same problems which are stated in issue #233, but for me it is nevermind if the link contanins /embed/ or /f/ in case of openload, both simply are not working for me. 

In SALTS (which i think also connects to Urlresolver) i get no premiumize.me links listed

When using the Addon Exodus, i can play Openload (HD) links via my premiumize account just fine. I think this is because the addon offers the possiblity to enter the premiumize userdata in the addon itself. 

Attached pls find my Kodi.log (1. attempt = Salts, 2. attempt xStream, 3. attempt Exodus (successfull)

Maybe i am plain too stupid, but i hope you can look into this matter. many thanks

brgds
saustark

[kodi-log.txt](https://github.com/tknorris/script.module.urlresolver/files/630931/kodi-log.txt)

**Comment by Viper2k4** [comment]
It seems like premiumize has a "Lab & experimentelle"-option which contains even more regexes and the rapidgator-regex is invalid =>"https?://(www\\.)?rapidgator\\.host/.*)"

At the first step its a premiumize error/bug and they have to fix it. But i also think the URLResolver could check every regex seperate so on wrong regex wouldn't break the whole process.

**Comment by saustark** [comment]
hi again,

meanwhile i did a lot of testing together with the guys at the xstream forum (viper2k4 is one of them), who helped me a lot.
They mentioned that i should turn off function caching in the url resolver, which unfortunately did not help But what did the "magic" for me in case of openload sources, was to turn out the lab and experimental features in my premiumize account page. Openload and Openload HD are working fine now,

The guys from xstream mentioned that the following log could be of use for you, so pls find same attached.

[kodi-log2.txt](https://github.com/tknorris/script.module.urlresolver/files/631373/kodi-log2.txt)

**Comment by tknorris** [comment]
I will update get_host to only throw out each regex that fails the re.compile()

**Comment by tknorris** [comment]
Change made [here](https://github.com/tknorris/script.module.urlresolver/commit/7cfc73dd6c137d1a9de2161af8d319cb51e00a95). It will be in the next version of urlreoslver.
