### ISSUE TITLE
Hi Sir,when I use SALTS I meet a problem

### ISSUE THREAD

**Issue by brmnh** [tknorris/script.module.urlresolver#24]
It seems the scrapper alluc in SALTS(version after 1.0.32) didnot work anymore.There is no alluc results in the search results.When I use version 1.0.32,there is no this problem.

**Comment by tknorris** [comment]
It's working fine here. I could use a log.

**Comment by brmnh** [comment]
Hi Sir,this is the log link:http://xbmclogs.com/pnvbekgw1

**Comment by tknorris** [comment]
It looks to me like you have pieces are parts of SALTS running from different versions. I think it's because you are trying to install SALTS directly from github which really isn't the right way to do it. github code can be/is frequently broken. You should really be installing from my beta repo if you want to keep up w/ the latest working code. If you switch to my beta repo, make sure you remove any trace of the current SALTS installs as they will cause strange errors.

**Comment by brmnh** [comment]
Hi Sir,when I install your beta repo,it says add-on does not have the correct structure.I cannot install it.

**Comment by tknorris** [comment]
Don't install from github, download the repo zip: https://github.com/tknorris/tknorris-beta-repo/blob/master/zips/repository.tknorris.beta/repository.tknorris.beta-1.0.5.zip?raw=true

and install that.

**Comment by brmnh** [comment]
Sir,should I install the latest script.module.urlresolver?

**Comment by tknorris** [comment]
Yes, it's much better to keep up to date on addons in general using repositories than trying to manually install everything from github.

**Comment by brmnh** [comment]
Did the repo have the latest script.module.urlresolver in it?

**Comment by tknorris** [comment]
Yes, all my repos have the latest TVA release of urlresolver.

**Comment by brmnh** [comment]
It seems alluc still doesnot work.

**Comment by brmnh** [comment]
In the search results there are none from alluc.

**Comment by tknorris** [comment]
Did you check the alluc website to see if there are any matching results for the search?

**Comment by brmnh** [comment]
I tried [you,john jones],the alluc website has an matching result,but from kodi there is none search result.

**Comment by tknorris** [comment]
I suspect that the filtering in the scraper is removing it because it doesn't exactly match the title.

**Comment by brmnh** [comment]
I remember when I use the 1.0.32 version,the search has one result from alluc scraper.

**Comment by tknorris** [comment]
That is pretty weird because there are no code changes to alluc between 1.0.32 and 1.0.35

**Comment by brmnh** [comment]
but now when I use 1.0.32again ,there is no result.

**Comment by brmnh** [comment]
It just sometime have a result,sometimes didnot.

**Comment by brmnh** [comment]
Hi Sir,are you online?
