### ISSUE TITLE
translation of the "Pair"-Diaglog

### ISSUE THREAD

**Issue by Viper2k4** [tknorris/script.module.urlresolver#241]
Heho,

what u think about an translation of the "Pair"-Diaglog? Many older germans (as example) dont speak english that well. So they only see an english message and think "oh ok the Hoster dont work".

We could also put the dialog part to and seperate helper function like this:

```
def get_pair_dialog(hoster_name, pair_url)
	header = '%s Stream Authorization' % (hoster_name)
	line1 = 'To play this video, authorization is required'
	line2 = 'Visit the link below to authorize the devices on your network:'
	line3 = '[B][COLOR blue]%s[/COLOR][/B] then click "Pair"' % (pair_url)
	return common.kodi.CountdownDialog(header, line1, line2, line3)
```
(Somthing like this with a bit translation ^^)

Greetings

**Comment by tknorris** [comment]
Yeah, it's a good idea. I need to add the code to use the translations first though. I'll add that this week and get the project created on transifex.

**Comment by alifrezser** [comment]
I suggest to use translations  also on the other dialoges and in settings too.

**Comment by tknorris** [comment]
URLResolver is now created on transifex if you want to get started on the translations: https://www.transifex.com/tv-addons/urlresolver/dashboard/

There are a few strings I haven't covered yet but we can add those in as we go.

**Comment by Viper2k4** [comment]
i will start the german translation as soon as possible.

But could u maybe compine:

"VidUP.me Stream Authorization"
"OpenLoad Stream Authorization"
"TheVideo.me Stream Authorization"

with something like:

"%s Stream Authorization"

I mean i dont have a problem to copy&past my translation. But just in case more hoster would like to use it, it would be a bit more universal.

**Comment by tknorris** [comment]
I considered that but I didn't want to force them all to be the same and I don't like the name that some of the resolvers use for the resolver. I figured it's minimal effort to create a unique header translation for each one.

**Comment by Viper2k4** [comment]
German translation is done

**Comment by tknorris** [comment]
the name of the resolver is used in the settings ids, so I can't change that without resetting everyone's settings. I'll take a look at adding the sep though.

**Comment by Viper2k4** [comment]
i mean here:

https://github.com/tknorris/script.module.urlresolver/blob/master/lib/urlresolver/__init__.py#L261

Thats only the an lsep. I think that should not even matter in anycase.

**Comment by tknorris** [comment]
I tried the title() thing and it looks weird.

**Comment by Viper2k4** [comment]
Mh yes it has problem with urls. A "Mail.Ru" look a bit weird. But it doesn't matter. Just an idear.

**Comment by tknorris** [comment]
FYI, I added the rest of the urlresolver strings. I think this covers almost all of them now. At some point I'll need to add all the ResolverError() ones but that's a bigger undertaking.

**Comment by Viper2k4** [comment]
Translate it. Btw. there single quota on the english version of "No link selected"

**Comment by tknorris** [comment]
Thanks, I'll fix it

**Comment by tknorris** [comment]
@Viper2k4 btw, you might want to uncheck the box on transifex so that your email doesn't show up in the .po files.

**Comment by Viper2k4** [comment]
i does ^^

**Comment by Viper2k4** [comment]
![unbenannt](https://cloud.githubusercontent.com/assets/15054322/21189602/81ae0772-c21f-11e6-9d73-3f422373b52a.PNG)

Seems like the Dialog dont auto-size that well :'(
(Also the Button is still hard coded)

**Comment by tknorris** [comment]
I'll fix the missing translation, but I can't do much about the resize issue. The real progress dialog has the same issue. The group the labels are in has a limit in size and if you force a wrap, it has to wrap to the same line. The only solution is to shorten the strings so they don't overlap.

**Comment by tknorris** [comment]
I suppose I could also turn off multiline wrap on the 1st and 2nd label...

**Comment by tknorris** [comment]
OK, I updated line1 and line2 to be non-wrap, and left line3 as wrappable. I also updated Cancel to use the existing translation. Looking at Estuary what they do is they actually make the lines a text box (rather than 3 lines) and concatenate them in code. That's a much bigger change though.

**Comment by Viper2k4** [comment]
Ok it cuts it off but even :)

I'm thinking about a shorter translationen but thats not that easy :/

**Comment by Viper2k4** [comment]
FYI, i found a fitting translation. You could update it if u want. I see transifex supports Character Limit. Maybe u could set this to ~70 to prevent this.
