### ISSUE TITLE
Hi Sir,when I use openload I met this problem

### ISSUE THREAD

**Issue by brmnh** [tknorris/script.module.urlresolver#243]
When I make a openload authorization,it gives me 4 hours to watch video,but now it gives only less than one hour to watch video.Sir,do you know this problem?Can you fix it?Thnaks very much.

**Comment by tknorris** [comment]
Sorry, it's openload's prerogative for how long /pairing lasts. If you don't like their streams or the pairing requirement you have to pick other sources.
