### ISSUE TITLE
Hi Sir,when I use SALTS addon on windows version kodi,I met a problem

### ISSUE THREAD

**Issue by brmnh** [tknorris/script.module.urlresolver#248]
the log file is this:

**Comment by brmnh** [comment]
09:08:23 T:3584  NOTICE: URLResolver: Initializing URLResolver version: 3.0.26
09:08:23 T:3584  NOTICE: Stream All The Sources: Version: |2.0.85| Queries: |{'mode': 'main'}|
09:08:23 T:3584  NOTICE: Stream All The Sources: Args: |['plugin://plugin.video.salts/', '1', '']|
09:08:23 T:3584  NOTICE: Stream All The Sources: Calling |main_menu| for mode |main| with pos args |[]| and kwargs |{}|
09:08:25 T:2372  NOTICE: URLResolver: Initializing URLResolver version: 3.0.26
09:08:26 T:2372  NOTICE: Stream All The Sources: Version: |2.0.85| Queries: |{'section': 'Movies', 'mode': 'browse'}|
09:08:26 T:2372  NOTICE: Stream All The Sources: Args: |['plugin://plugin.video.salts/', '2', '?mode=browse&section=Movies']|
09:08:26 T:2372  NOTICE: Stream All The Sources: Calling |browse_menu| for mode |browse| with pos args |['Movies']| and kwargs |{}|
09:08:28 T:112  NOTICE: URLResolver: Initializing URLResolver version: 3.0.26
09:08:29 T:112  NOTICE: Stream All The Sources: Version: |2.0.85| Queries: |{'section': 'Movies', 'mode': 'trending'}|
09:08:29 T:112  NOTICE: Stream All The Sources: Args: |['plugin://plugin.video.salts/', '3', '?mode=trending&section=Movies']|
09:08:29 T:112  NOTICE: Stream All The Sources: Calling |browse_trending| for mode |trending| with pos args |['Movies']| and kwargs |{}|
09:08:29 T:112   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: 'function' object has no attribute '__getitem__'
                                            Traceback (most recent call last):
                                              File "C:\Users\john\AppData\Roaming\Kodi\addons\plugin.video.salts\default.py", line 2584, in <module>
                                                sys.exit(main())
                                              File "C:\Users\john\AppData\Roaming\Kodi\addons\plugin.video.salts\default.py", line 2575, in main
                                                url_dispatcher.dispatch(mode, queries)
                                              File "C:\Users\john\AppData\Roaming\Kodi\addons\script.module.tknorris.shared\lib\url_dispatcher.py", line 97, in dispatch
                                                self.func_registry[mode](*args, **kwargs)
                                              File "C:\Users\john\AppData\Roaming\Kodi\addons\plugin.video.salts\default.py", line 486, in browse_trending
                                                make_dir_from_list(section, list_data, query={'mode': MODES.TRENDING, 'section': section}, page=page)
                                              File "C:\Users\john\AppData\Roaming\Kodi\addons\plugin.video.salts\default.py", line 2214, in make_dir_from_list
                                                liz, liz_url = make_item(section_params, show, menu_items)
                                              File "C:\Users\john\AppData\Roaming\Kodi\addons\plugin.video.salts\default.py", line 2429, in make_item
                                                liz = utils.make_list_item(label, show, utils2.make_art)
                                              File "C:\Users\john\AppData\Roaming\Kodi\addons\script.module.tknorris.shared\lib\utils.py", line 46, in make_list_item
                                                listitem = xbmcgui.ListItem(label, iconImage=art['thumb'], thumbnailImage=art['thumb'])
                                            TypeError: 'function' object has no attribute '__getitem__'
                                            -->End of Python script error report<--
09:08:29 T:1484   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.salts/?mode=trending&section=Movies
09:08:29 T:1484   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.salts/?mode=trending&section=Movies) failed
09:08:34 T:3060  NOTICE: URLResolver: Initializing URLResolver version: 3.0.26
09:08:35 T:3060  NOTICE: Stream All The Sources: Version: |2.0.85| Queries: |{'section': 'Movies', 'mode': 'recent_search'}|
09:08:35 T:3060  NOTICE: Stream All The Sources: Args: |['plugin://plugin.video.salts/', '4', '?mode=recent_search&section=Movies']|
09:08:35 T:3060  NOTICE: Stream All The Sources: Calling |recent_searches| for mode |recent_search| with pos args |['Movies']| and kwargs |{}|
09:08:36 T:876  NOTICE: URLResolver: Initializing URLResolver version: 3.0.26
09:08:37 T:876  NOTICE: Stream All The Sources: Version: |2.0.85| Queries: |{'query': 'mel gibson', 'section': 'Movies', 'mode': 'search_results'}|
09:08:37 T:876  NOTICE: Stream All The Sources: Args: |['plugin://plugin.video.salts/', '5', '?mode=search_results&query=mel%20gibson&section=Movies']|
09:08:37 T:876  NOTICE: Stream All The Sources: Calling |search_results| for mode |search_results| with pos args |['Movies', 'mel gibson']| and kwargs |{}|
09:08:38 T:876   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: 'function' object has no attribute '__getitem__'
                                            Traceback (most recent call last):
                                              File "C:\Users\john\AppData\Roaming\Kodi\addons\plugin.video.salts\default.py", line 2584, in <module>
                                                sys.exit(main())
                                              File "C:\Users\john\AppData\Roaming\Kodi\addons\plugin.video.salts\default.py", line 2575, in main
                                                url_dispatcher.dispatch(mode, queries)
                                              File "C:\Users\john\AppData\Roaming\Kodi\addons\script.module.tknorris.shared\lib\url_dispatcher.py", line 97, in dispatch
                                                self.func_registry[mode](*args, **kwargs)
                                              File "C:\Users\john\AppData\Roaming\Kodi\addons\plugin.video.salts\default.py", line 1130, in search_results
                                                make_dir_from_list(section, results, query={'mode': MODES.SEARCH_RESULTS, 'section': section, 'query': query}, page=page)
                                              File "C:\Users\john\AppData\Roaming\Kodi\addons\plugin.video.salts\default.py", line 2214, in make_dir_from_list
                                                liz, liz_url = make_item(section_params, show, menu_items)
                                              File "C:\Users\john\AppData\Roaming\Kodi\addons\plugin.video.salts\default.py", line 2429, in make_item
                                                liz = utils.make_list_item(label, show, utils2.make_art)
                                              File "C:\Users\john\AppData\Roaming\Kodi\addons\script.module.tknorris.shared\lib\utils.py", line 46, in make_list_item
                                                listitem = xbmcgui.ListItem(label, iconImage=art['thumb'], thumbnailImage=art['thumb'])
                                            TypeError: 'function' object has no attribute '__getitem__'
                                            -->End of Python script error report<--
09:08:38 T:1484   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.salts/?mode=search_results&query=mel%20gibson&section=Movies
09:08:38 T:1484   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.salts/?mode=search_results&query=mel%20gibson&section=Movies) failed
09:08:38 T:3468  NOTICE: URLResolver: Initializing URLResolver version: 3.0.26
09:08:38 T:3468  NOTICE: Stream All The Sources: Version: |2.0.85| Queries: |{'section': 'Movies', 'mode': 'recent_search'}|
09:08:38 T:3468  NOTICE: Stream All The Sources: Args: |['plugin://plugin.video.salts/', '6', '?mode=recent_search&section=Movies']|
09:08:38 T:3468  NOTICE: Stream All The Sources: Calling |recent_searches| for mode |recent_search| with pos args |['Movies']| and kwargs |{}|
09:08:43 T:1484  NOTICE: Storing total System Uptime
09:08:43 T:1484  NOTICE: Saving settings
09:08:43 T:1484  NOTICE: stop all
09:08:43 T:1484  NOTICE: stop player
09:08:43 T:1484  NOTICE: ES: Stopping event server
09:08:43 T:1484  NOTICE: stopping upnp
09:08:43 T:1484  NOTICE: WebServer: Stopped the webserver
09:08:43 T:4008  NOTICE: ES: UDP Event server stopped
09:08:43 T:1484  NOTICE: stop sap announcement listener
09:08:43 T:1484  NOTICE: clean cached files!
09:08:43 T:1484  NOTICE: unload skin
09:08:43 T:4092  NOTICE: DudeHere Common Routines Service: Service stopping...
09:08:43 T:2652  NOTICE: Stream All The Sources: Service: shutting down...
09:08:43 T:1484  NOTICE: stopped
09:08:43 T:1484  NOTICE: destroy
09:08:43 T:1484  NOTICE: closing down remote control service
09:08:43 T:1484  NOTICE: unload sections
09:08:43 T:1484  NOTICE: special://profile/ is mapped to: special://masterprofile/
09:08:44 T:1484  NOTICE: destroy
09:08:44 T:1484 WARNING: Attempted to remove window 10013 from the window manager when it didn't exist
09:08:44 T:1484 WARNING: Attempted to remove window 10014 from the window manager when it didn't exist
09:08:44 T:1484 WARNING: Attempted to remove window 10015 from the window manager when it didn't exist
09:08:44 T:1484 WARNING: Attempted to remove window 10016 from the window manager when it didn't exist
09:08:44 T:1484 WARNING: Attempted to remove window 10017 from the window manager when it didn't exist
09:08:44 T:1484 WARNING: Attempted to remove window 10018 from the window manager when it didn't exist
09:08:44 T:1484 WARNING: Attempted to remove window 10019 from the window manager when it didn't exist
09:08:44 T:1484 WARNING: Attempted to remove window 10021 from the window manager when it didn't exist
09:08:44 T:1484 WARNING: Attempted to remove window 10107 from the window manager when it didn't exist
09:08:44 T:1484 WARNING: Attempted to remove window 10115 from the window manager when it didn't exist
09:08:44 T:1484 WARNING: Attempted to remove window 10104 from the window manager when it didn't exist
09:08:44 T:1484  NOTICE: closing down remote control service
09:08:44 T:1484  NOTICE: unload sections
09:08:44 T:1484  NOTICE: application stopped...
09:08:44 T:1484   ERROR: dllFreeLibrary - Invalid hModule specified

**Comment by brmnh** [comment]
Sir,can you fix it?Thanks very much.

**Comment by tknorris** [comment]
https://forums.tvaddons.ag/tknorris-release-repository/32462-stream-sources-aka-salts-v2-0-85-2016-03-30-a-131.html#post389817
