### ISSUE TITLE
Hi Sir,can you use SALTS to search film [you,john jones]

### ISSUE THREAD

**Issue by brmnh** [tknorris/script.module.urlresolver#25]
to see if there is an alluc result?Thanks.

**Comment by tknorris** [comment]
At the moment I'm getting back an Key Error/Rate Limit error from the alluc API so no results are coming back. I'll check w/ the alluc admin on it.

**Comment by brmnh** [comment]
Thanks Sir.

**Comment by brmnh** [comment]
Hi Sir,can you get search result from alluc now?

**Comment by tknorris** [comment]
Nope, still getting the error.

**Comment by brmnh** [comment]
Is the scraper alluc broken?

**Comment by tknorris** [comment]
No, it's the api key. allux rate limits how frequently a given api key can be used and it looks like mine is being used too frequently. I won't be able to resolve it until I get a response back from the alluc admin though.

**Comment by brmnh** [comment]
I just got the message:no sources found.

**Comment by brmnh** [comment]
Hi Sir,can you get search result from alluc now?

**Comment by tknorris** [comment]
I will let you know when I have new information...
