### ISSUE TITLE
Hi Sir,I just buy real debrid premium account

### ISSUE THREAD

**Issue by brmnh** [tknorris/script.module.urlresolver#255]
Real debrid website says it support the openload link.But when I already authorize real debrid in urlresolver section,when I play openload link in salts addon,it still gives a popup that says I should pair it.Sir since I already use real debrid premium service,can I skip the openload pair popup?When I play thevideo.me link in salts addon,it did not show popup.When I use exodus addon and play openload links in it,it also does not show popups.The problem is openload links in salts addon.Sir can you fix it?Or can you  talk,with openload website that  the real debrid premium account user could skip the pair popup of the openload links in salts addon.Thanks very much.

**Comment by brmnh** [comment]
Since openload website is in partnership with real debrid,when I buy real debrid premium account,I should have skipped the openload pair popup.

**Comment by brmnh** [comment]
The thevideo.me website already done this.

**Comment by brmnh** [comment]
openload with exodus addon is fine.the problem is openload with urlresolver and salts.

**Comment by tknorris** [comment]
make sure the set the RD priority lower than openload and it should work fine. If not, post a log w/ debug on of playing a openload link.

**Comment by brmnh** [comment]
Sir,it just works fine right now.But I can not make sure that it works 24hours one day.When it does not work,I will post a log file txt.
