### ISSUE TITLE
'rapidvideo.com' changed the name to 'raptu.com'

### ISSUE THREAD

**Issue by antrrax** [tknorris/script.module.urlresolver#257]
The host 'rapidvideo.com' changed the name to 'raptu.com', someone could fix the script, for urlresolver to work again with that site.
 Thank you

**Comment by azzy9** [comment]
Hi,

Looks like the fix has already been made in "lib/urlresolver/plugins/rapidvideocom.py" to add "raptu.com" to the plugin.
So you will need to wait for the next release of urlresolver.

`domains = ["rapidvideo.com", "raptu.com"]
pattern = '(?://|\.)((?:rapidvideo|raptu)\.com)/(?:embed/|\?v=)?([0-9A-Za-z]+)'`

**Comment by tknorris** [comment]
fixed in https://github.com/tknorris/script.module.urlresolver/commit/58e1ff5dc7beec488a87b160b03472ab8602d932
