### ISSUE TITLE
http://thevid.net/

### ISSUE THREAD

**Issue by antrrax** [tknorris/script.module.urlresolver#258]
This host is widely used in my country, it can be supported:
http://thevid.net/

Thanks

**Comment by tknorris** [comment]
added: https://github.com/tknorris/script.module.urlresolver/commit/89f418e7ed3b9b465007534e866dfad37fc22efb

**Comment by sonaldynho** [comment]
http://thevid.net/ stop working a week ago, can u fix??
it is a very good host

**Comment by tknorris** [comment]
fix pushed, will show up in the next build.

**Comment by sonaldynho** [comment]
Thanks tknorris I love your work do u have a donate link ??

**Comment by tknorris** [comment]
nah, if you really want you can send me a real-debrid or premiumize voucher via PM on the tva forum. Otherwise, thanks is plenty.

**Comment by sonaldynho** [comment]
O Just want to help a little, PayPal is what I use. If u have a PayPal. me I can help
