### ISSUE TITLE
Hi Sir,I met a problem.

### ISSUE THREAD

**Issue by brmnh** [tknorris/script.module.urlresolver#264]
When I watch kodi,I have to always use vpn(or similar tools).When I use some vpns,I can authorize it with real debrid premium account,so that when I watch videos from openload I do not meet pair popup.But when I use some other vpns(or ips),I however can authorize it with real debrid premium account,but I still meet the pair popup.Sir,can you tell me what is the problem.It seems for some ip addresses real debrid premium account works,for some other ip addresses it does not work.Sir can you fix it?

**Comment by tknorris** [comment]
That sounds like a VPN/RD problem and doesn't really have anything to do w/ urlresolver.
