### ISSUE TITLE
streamcloud.eu

### ISSUE THREAD

**Issue by elpocko** [tknorris/script.module.urlresolver#277]
Streamcloud not working for weeks.

**Comment by Viper2k4** [comment]
did u have an example? For me its just working as excepted

**Comment by tknorris** [comment]
I'm working on it now.

**Comment by Viper2k4** [comment]
mh ok. I just test two links and both are working. So it seems not broken at all. But ok if u are working on it im gone ^^

**Comment by tknorris** [comment]
For me, w/o the 10 second pause, nothing would resolve properly.
