### ISSUE TITLE
My mail ru

### ISSUE THREAD

**Issue by PBear90** [tknorris/script.module.urlresolver#288]
Since the last update it's working great but there is a few which don't play, this is one.. 

http://m.my.mail.ru/mailua/rem_86/video/79/2141.html

It's obviously the mailua part in the url. Could this be added please? ☺

**Comment by tknorris** [comment]
@jsergio123 want to take a look at this?

**Comment by jsergio123** [comment]
@PBear90 your URL contains multiple videos on one page. The plugin is meant to resolver a single video on a single page.

**Comment by tknorris** [comment]
Should I close the issue?

**Comment by jsergio123** [comment]
@tknorris no sorry my bad, he wants the first video.

**Comment by tknorris** [comment]
Fixed in #289

**Comment by tknorris** [comment]
@jsergio123 thanks!
