### ISSUE TITLE
Hi Sir,have you got the alluc problem fixed?

### ISSUE THREAD

**Issue by brmnh** [tknorris/script.module.urlresolver#29]

**Comment by tknorris** [comment]
Yes, it should be working.

**Comment by brmnh** [comment]
Thanks Sir.

**Comment by brmnh** [comment]
Sir,when I try movie [the brass bottle] in SALTS 1.0.32 version,It has one alluc result,but when I use the latest SALTS version,It has no alluc result.I install latest version from your repository.

**Comment by tknorris** [comment]
Thanks for letting me know, it looks like alluc needs to make a change to fix this. I'll let you know when it's fixed.

**Comment by brmnh** [comment]
Thanks.
