### ISSUE TITLE
Please could you fix upload.af/uploadx.org/uploadz.co as the captcha is not working.

### ISSUE THREAD

**Issue by Sanjjay** [tknorris/script.module.urlresolver#296]
Please could you fix upload.af/uploadx.org/uploadz.co as the captcha is not working.

Using Kodi 16.1 and Kodi 17.1

Thank you!

**Comment by tknorris** [comment]
If the captcha call is returning a error 400, then the hosts have disabled non-js fallback via captcha. It can't be fixed. If you want to use those sources, buy a debrid subscription.

**Comment by Sanjjay** [comment]
Thank you for having a look.

I might be wrong but reading a while back on tvaddons.ag, I thought the captcha was an agreement with you for kodi to access the hosts same as pairing for openload.

I just dont feel the need to buy debrid as most links are free and available on the internet, it is alot easier and better to view and control in kodi than a browser.

**Comment by tknorris** [comment]
You are mistaken. /pair is the agreement w/ some hosts to allow access from kodi. The captcha's are put in place specifically to block kodi.

**Comment by Sanjjay** [comment]
sorry for misunderstanding thanks for looking anyway hope they remove the non-js fallback in future.

**Comment by Sanjjay** [comment]
These websites have removed the captcha and changed the url to upload.mn/uploadx.link/uploadz.org, any chance they could be fixed in urlresolver.

**Comment by tknorris** [comment]
fixed pushed, will be in the next release

**Comment by Sanjjay** [comment]
Thank you!!! much appreciated.
