### ISSUE TITLE
veeHD resovle failure problem

### ISSUE THREAD

**Issue by brmnh** [tknorris/script.module.urlresolver#3]
Hi sir,I find the problem seem to be:the videos of veeHD.com almost all can be resolved and played,the problem is when I continously play the videos of veeHD.com,(for example 20 videos)it will finally report resolving failure.I have to reinstall the script.module.urlresolver to fix this problem.Sir,can you make some  changes to the script so that no need to reinstall the script?Thanks.

**Comment by brmnh** [comment]
or maybe the problem is I am using external player?

**Comment by tknorris** [comment]
It's more likely that veehd eventually temporarily blocks you after so many videos. Nothing happens in the script on video 21 that doesn't happen on video 1.
