### ISSUE TITLE
Vk.com and two requests. @PBear90 

### ISSUE THREAD

**Issue by PBear90** [tknorris/script.module.urlresolver#310]
Hi could these two sites please be added to the urlresolver. 

https://biqle.ru/watch/-93235433_171392839

http://www.soku.com/m/y/video?q=no+mercy+2002#loaded

the soku site seems to change url when you click a video but the link above is where I found the videos so once u click it you will see. 

Also vk.com seems to be down, could this be looked into please. It's an important source for me. 

Massive thanks for all you guys do. 

PBear

**Comment by tknorris** [comment]
I'll take a look at biqle and vk.com, but soku.com is not a hoster.

**Comment by tknorris** [comment]
I took a look at this. So, first off, vk.com is working fine. If it's not working for you then it's a geographic issue. Regarding bigle, I'm pretty sure they are re-sharing vk.com videos but they have a bunch of code dedicated to hiding how they are pulling the vk.com videos but I'm pretty sure they are doing some authentication to do so. It would be a large amount of code to reproduce it so it's probably not really worth it. If it's something you'd be interested in contributing, I'm happy to accept it, but it would take more time than I'm willing to spend on it.

**Comment by PBear90** [comment]
On soku the video links are showing as http://v.youku.com/v_show/id_XMTY3NTQyNjYyNA==.html?from=s7.8-1.2&spm=a2h0k.8191393.bodydiv.5!2~5!8~A

Not sure if that can be added... Vk is odd, seems to be effecting some people in certain ares but not all the country. Odd one. 

Don't worry about that other one then mate. Thanks for the reply 👍
