### ISSUE TITLE
Dailymotion showing ads

### ISSUE THREAD

**Issue by oenm** [tknorris/script.module.urlresolver#319]
Dailymotion is randomly showing ads instead of the intended video, can watch 1 or 2 videos and then all videos are ads.

**Comment by tknorris** [comment]
hmm, I haven't seen that I've tried watching the same video 3 or 4 times and it shows the video every time.

**Comment by oenm** [comment]
the video in question is longer than 30 mins, I wonder if its time based

**Comment by tknorris** [comment]
I think the one I was checking was 55 mins long, but I never watched the full video...

**Comment by dsoh** [comment]
Hi sorry, this was an issue with a weird character parsed in the url, totally my fault didn't look closer.

it just sent me 5 random dailymotion videos to watch in place of what i wanted due to the character

Please close this

**Comment by tknorris** [comment]
we might need to do a better job validating that the media_id actually exists. I'll check that. I'll close this though.
