### ISSUE TITLE
Hi Sir,can you change the kodi default playlist timeout length?

### ISSUE THREAD

**Issue by brmnh** [tknorris/script.module.urlresolver#32]
Thanks.

**Comment by brmnh** [comment]
I feel it too short,many video cannot be played within this time length.

**Comment by tknorris** [comment]
There is no setting for it to be changed. It's hard coded into Kodi.

Also, I don't know if you noticed, but I added a uid/pw option to the alluc scraper now so you can put in your alluc username and password to stop getting the "too man requests" error.

**Comment by brmnh** [comment]
Thanks Sir,I will try.
