### ISSUE TITLE
Hi Sir,when I use SALTS I got a problem

### ISSUE THREAD

**Issue by brmnh** [tknorris/script.module.urlresolver#34]
when I watch movies [the devil commands] and [the ghoul],I just cannot play them from the veeHD resolver of the scraper alluc.I changed several vpn,but it still cannot play.Sir,can you play these two movies from SALTS in resolver veeHD of scraper alluc?Or can you get any way to play these two movies?Thanks Sir.

**Comment by tknorris** [comment]
For me the 1st one worked, but the 2nd one did not. The problem in general though is the usual one: veehd is just really slow and kodi times out. Even for the first one, it just barely started playing.
