### ISSUE TITLE
anime-loads.org (de) + Openload.co and real-debrid fail

### ISSUE THREAD

**Issue by Kampfader** [tknorris/script.module.urlresolver#349]
hi,
using the last urlresolver..

Anime = [ [](url)](http://www.anime-loads.org/media/kurogane-communication)
S01E01 on website online for openload.co

im go to Kodi 17.3 (Exodus Addon)
Searching for this Anime and have 3 Options, only from anime-loads.org. 

1. Real-Debrid (Openload)
2. Streamcload
3. Openload

and yes, i have added my real debrid acc to urlresolver.
im Starting the first one (Real-Debrid) his jumping to Streamcload
im starting the Openload option his jump to Streamcload

kodi.log = [ [](url)](https://pastebin.com/tyGAcK20)

thanks

**Comment by tknorris** [comment]
I'll look at it when I get some time.

**Comment by Viper2k4** [comment]
So i check it. Thats an Bug in Exodus. Or more specific in the animeloads-scrapper. This has to be fixed in exodus. So no issue here.

**Comment by tknorris** [comment]
Thanks, I'll close this then.
