### ISSUE TITLE
helpers function not working as expected

### ISSUE THREAD

**Issue by Gujal00** [tknorris/script.module.urlresolver#352]
in tvlogy.py plugin I was using the following to scrape the url
sources = helpers.scrape_sources(html)
strurl = helpers.pick_source(sources)

For some reason this is not picking the url correctly any more. If I remove those and use my own regex, it certainly works, but would like to use the helpers function
Sample URL - `http://tvlogy.to/watch.php?v=YD38275`

This is the html code snippet
`clip: {
            sources: [
                { type: "application/x-mpegurl",
                    src:  "http://proxy-071.dc3.dailymotion.com/sec(e429c46ea5b661bb35dfd8cc15278e1a)/video/569/036/345630965_mp4_h264_aac_hd_2.m3u8" }
            ]
        }`

Please advise if you can look at the helpers function or should I do a pull request for tvlogy`with my own regex.

Thanks

**Comment by tknorris** [comment]
I'll take a look. I cleaned up one of the regex recently and it might have affected this resolver. The problem is the old regex was marching too often.

**Comment by Gujal00** [comment]
Thanks

**Comment by Viper2k4** [comment]
Had the same Issue with Streamcloud. And up in this:

https://github.com/tknorris/script.module.urlresolver/blob/master/lib/urlresolver/plugins/streamcloud.py#L51

Maybe we should take a look and some more scrapers.

**Comment by tknorris** [comment]
I think the problem is slightly different because for streamcloud the isuse was "file:" but for tvlogy it's src: which is a different regex. The problem with file/url regex that they are so generic, they match all kind of other elements in the page. e.g. (next_url=blah.html matches the old regex)

**Comment by tknorris** [comment]
Looking at the problem, I think the solution is the same though, we need to pass an alternate regex to scrape_sources. Once again, "src:" is just too generic to have all resolvers using it. I'll update the resolver now.

**Comment by Gujal00** [comment]
Thanks
I see that you have used the following
`patterns=[',\s*src\s*:\s*"(?P<url>[^"]+)']`
However on the html, there is no space between src and : 
Will the patter still match?
Thanks

**Comment by Viper2k4** [comment]
\s = space need to be occur
\s* = space need to occur 0 or more

So yes its just more the "safe" version if tvlogy adds an space there.

**Comment by Gujal00** [comment]
Fantastic, I will close the issue then. Thanks
