### ISSUE TITLE
Hi Sir,when I use salts I met this problem

### ISSUE THREAD

**Issue by brmnh** [tknorris/script.module.urlresolver#366]
Sorry,I can not post log file to tvaddons.I have to post it here.Sorry Sir.

**Comment by brmnh** [comment]
This is the log.

**Comment by brmnh** [comment]
11:32:27 T:1933888776  NOTICE: special://profile/ is mapped to: special://masterprofile/
11:32:27 T:1933888776  NOTICE: -----------------------------------------------------------------------
11:32:27 T:1933888776  NOTICE: Starting SPMC (16.4-2 Git:2016-08-15-46f733d-dirty). Platform: Android ARM 32-bit
11:32:27 T:1933888776  NOTICE: Using Release SPMC x32 build
11:32:27 T:1933888776  NOTICE: SPMC compiled Aug 15 2016 by GCC 4.8.0 for Android ARM 32-bit API level 17 (API level 17)
11:32:27 T:1933888776  NOTICE: Running on Tmall MagicBox2 with Android 3.0.6-RS-20160831.0951 API level 19, kernel: Linux ARM 32-bit version 3.10.33
11:32:27 T:1933888776  NOTICE: FFmpeg version: 2.8.6-kodi-2.8.6-Jarvis-16.0-spmc
11:32:27 T:1933888776  NOTICE: Host CPU: ARMv7 Processor rev 1 (v7l), 4 cores available
11:32:27 T:1933888776  NOTICE: Product: MagicBox2, Device: MagicBox2, Board: MagicBox2 - Manufacturer: Tmall, Brand: MBX, Model: MagicBox2, Hardware: amlogic
11:32:27 T:1933888776  NOTICE: External storage path = /storage/emulated/0; status = ok
11:32:27 T:1933888776  NOTICE: HasTouchScreen = no
11:32:27 T:1933888776  NOTICE: ARM Features: Neon enabled
11:32:27 T:1933888776  NOTICE: special://xbmc/ is mapped to: /data/data/com.semperpax.spmc16/cache/apk/assets
11:32:27 T:1933888776  NOTICE: special://xbmcbin/ is mapped to: /data/data/com.semperpax.spmc16/cache/apk/assets
11:32:27 T:1933888776  NOTICE: special://masterprofile/ is mapped to: /storage/emulated/0/Android/data/com.semperpax.spmc16/files/.spmc/userdata
11:32:27 T:1933888776  NOTICE: special://home/ is mapped to: /storage/emulated/0/Android/data/com.semperpax.spmc16/files/.spmc
11:32:27 T:1933888776  NOTICE: special://temp/ is mapped to: /storage/emulated/0/Android/data/com.semperpax.spmc16/files/.spmc/temp
11:32:27 T:1933888776  NOTICE: The executable running is:
11:32:27 T:1933888776  NOTICE: Local hostname: localhost
11:32:27 T:1933888776  NOTICE: Log File is located: /storage/emulated/0/Android/data/com.semperpax.spmc16/files/.spmc/temp/spmc.log
11:32:27 T:1933888776  NOTICE: -----------------------------------------------------------------------
11:32:27 T:1933888776  NOTICE: load settings...
11:32:27 T:1933888776   DEBUG: CSettings: loaded settings definition from special://xbmc/system/settings/settings.xml
11:32:27 T:1933888776 WARNING: CSettingInt: unknown options filler "audiocdactions" of "audiocds.autoaction"
11:32:27 T:1933888776   DEBUG: CSettings: loaded settings definition from special://xbmc/system/settings/android.xml
11:32:27 T:1933888776   DEBUG: AESinkAUDIOTRACK - 32000 supported
11:32:27 T:1933888776   DEBUG: AESinkAUDIOTRACK - 44100 supported
11:32:27 T:1933888776   DEBUG: AESinkAUDIOTRACK - 48000 supported
11:32:27 T:1933888776  NOTICE: Found 1 Lists of Devices
11:32:27 T:1933888776  NOTICE: Enumerated AUDIOTRACK devices:
11:32:27 T:1933888776  NOTICE:     Device 1
11:32:27 T:1933888776  NOTICE:         m_deviceName      : AudioTrackPCM
11:32:27 T:1933888776  NOTICE:         m_displayName     : Android
11:32:27 T:1933888776  NOTICE:         m_displayNameExtra: PCM
11:32:27 T:1933888776  NOTICE:         m_deviceType      : AE_DEVTYPE_PCM
11:32:27 T:1933888776  NOTICE:         m_channels        : FL,FR,FC,LFE,BL,BR
11:32:27 T:1933888776  NOTICE:         m_sampleRates     : 32000,44100,48000
11:32:27 T:1933888776  NOTICE:         m_dataFormats     : AE_FMT_S16LE
11:32:27 T:1933888776  NOTICE:     Device 2
11:32:27 T:1933888776  NOTICE:         m_deviceName      : AudioTrackPT
11:32:27 T:1933888776  NOTICE:         m_displayName     : Android
11:32:27 T:1933888776  NOTICE:         m_displayNameExtra: IEC Passthrough
11:32:27 T:1933888776  NOTICE:         m_deviceType      : AE_DEVTYPE_HDMI
11:32:27 T:1933888776  NOTICE:         m_channels        : FL,FR,FC,LFE,BL,BR
11:32:27 T:1933888776  NOTICE:         m_sampleRates     : 32000,44100,48000
11:32:27 T:1933888776  NOTICE:         m_dataFormats     : AE_FMT_AC3,AE_FMT_DTS
11:32:27 T:1933888776   DEBUG: CSkinSettings: no <skinsettings> tag found
11:32:27 T:1933888776  NOTICE: No settings file to load (special://xbmc/system/advancedsettings.xml)
11:32:27 T:1933888776  NOTICE: No settings file to load (special://masterprofile/advancedsettings.xml)
11:32:27 T:1933888776  NOTICE: Default DVD Player: dvdplayer
11:32:27 T:1933888776  NOTICE: Default Video Player: dvdplayer
11:32:27 T:1933888776  NOTICE: Default Audio Player: paplayer
11:32:27 T:1933888776  NOTICE: Disabled debug logging due to GUI setting. Level 0.
11:32:27 T:1933888776  NOTICE: Log level changed to "LOG_LEVEL_NORMAL"
11:32:27 T:1933888776  NOTICE: CMediaSourceSettings: loading media sources from special://masterprofile/sources.xml
11:32:27 T:1933888776  NOTICE: Loading player core factory settings from special://xbmc/system/playercorefactory.xml.
11:32:27 T:1933888776  NOTICE: Loaded playercorefactory configuration
11:32:27 T:1933888776  NOTICE: Loading player core factory settings from special://masterprofile/playercorefactory.xml.
11:32:27 T:1933888776  NOTICE: special://masterprofile/playercorefactory.xml does not exist. Skipping.
11:32:27 T:1933888776  NOTICE: Running database version Addons20
11:32:27 T:1933888776  NOTICE: ADDONS: Using repository repository.tknorris.beta
11:32:27 T:1933888776  NOTICE: ADDONS: Using repository repository.xbmc.org
11:32:27 T:1933888776  NOTICE: ADDONS: Using repository repository.xbmc-addons-chinese
11:32:27 T:1933888776  NOTICE: ADDONS: Using repository repository.xbmchub
11:32:27 T:1933888776  NOTICE: ADDONS: Using repository repository.noobsandnerds
11:32:27 T:1933888776  NOTICE: ADDONS: Using repository repository.elysium
11:32:27 T:1933888776  NOTICE: virtual bool CWinSystemEGL::InitWindowSystem(): Using EGL Implementation: amlandroid
11:32:27 T:1933888776  NOTICE: CEGLNativeTypeAndroid: Current resolution: 1920x1080 @ 60.000004 - Full Screen
11:32:27 T:1933888776  NOTICE: Previous line repeats 1 times.
11:32:27 T:1933888776  NOTICE: Found resolution 1920 x 1080 for display 0 with 720 x 480 @ 60.000000 Hz
11:32:27 T:1933888776  NOTICE: Found resolution 1920 x 1080 for display 0 with 1280 x 720 @ 60.000000 Hz
11:32:27 T:1933888776  NOTICE: Found resolution 1920 x 1080 for display 0 with 1920 x 1080i @ 60.000000 Hz
11:32:27 T:1933888776  NOTICE: Found resolution 1920 x 1080 for display 0 with 1920 x 1080 @ 60.000000 Hz
11:32:27 T:1933888776  NOTICE: Found resolution 1920 x 1080 for display 0 with 1280 x 720 @ 50.000000 Hz
11:32:27 T:1933888776  NOTICE: Found resolution 1920 x 1080 for display 0 with 1920 x 1080i @ 50.000000 Hz
11:32:27 T:1933888776  NOTICE: Found resolution 1920 x 1080 for display 0 with 1920 x 1080 @ 50.000000 Hz
11:32:27 T:1933888776  NOTICE: Found resolution 1920 x 1080 for display 0 with 1920 x 1080 @ 24.000000 Hz
11:32:27 T:1933888776  NOTICE: Found (1920x1080@60.000000) at 19, setting to RES_DESKTOP at 16
11:32:27 T:1933888776  NOTICE: Checking resolution 16
11:32:27 T:1933888776  NOTICE: GL_VENDOR = ARM
11:32:27 T:1933888776  NOTICE: GL_RENDERER = Mali-450 MP
11:32:27 T:1933888776  NOTICE: GL_VERSION = OpenGL ES 2.0
11:32:27 T:1933888776  NOTICE: GL_SHADING_LANGUAGE_VERSION = OpenGL ES GLSL ES 1.00
11:32:27 T:1933888776  NOTICE: GL_EXTENSIONS = GL_EXT_debug_marker GL_OES_texture_npot GL_OES_compressed_ETC1_RGB8_texture GL_OES_standard_derivatives GL_OES_EGL_image GL_OES_depth24 GL_ARM_rgba8 GL_ARM_mali_shader_binary GL_OES_depth_texture GL_OES_packed_depth_stencil GL_EXT_texture_format_BGRA8888 GL_OES_vertex_half_float GL_EXT_blend_minmax GL_OES_EGL_image_external GL_OES_EGL_sync GL_OES_rgb8_rgba8 GL_EXT_multisampled_render_to_texture GL_EXT_discard_framebuffer GL_OES_get_program_binary GL_ARM_mali_program_binary GL_EXT_shader_texture_lod GL_EXT_robustness GL_OES_depth_texture_cube_map GL_KHR_debug
11:32:27 T:1933888776  NOTICE: CEGLNativeTypeAndroid: Current resolution: 1920x1080 @ 60.000004 - Full Screen
11:32:27 T:1933888776  NOTICE: Running database version Addons20
11:32:27 T:1933888776  NOTICE: Running database version ViewModes6
11:32:27 T:1933888776  NOTICE: Running database version Textures13
11:32:27 T:1933888776  NOTICE: Running database version MyMusic56
11:32:28 T:1933888776  NOTICE: Running database version MyVideos99
11:32:28 T:1933888776  NOTICE: Running database version TV29
11:32:28 T:1933888776  NOTICE: Running database version Epg11
11:32:28 T:1933888776 WARNING: JSONRPC: Could not parse type "Setting.Details.SettingList"
11:32:28 T:1933888776  NOTICE: ActiveAE DSP - starting
11:32:28 T:1933888776  NOTICE: initialize done
11:32:28 T:1933888776  NOTICE: Running the application...
11:32:28 T:1933888776  NOTICE: starting zeroconf publishing
11:32:28 T:1933888776  NOTICE: WebServer: Started the webserver
11:32:28 T:1933888776  NOTICE: starting upnp client
11:32:28 T:1933888776  NOTICE: CEGLNativeTypeAndroid: Current resolution: 1920x1080 @ 60.000004 - Full Screen
11:32:28 T:1933888776  NOTICE: GL_VENDOR = ARM
11:32:28 T:1933888776  NOTICE: GL_RENDERER = Mali-450 MP
11:32:28 T:1933888776  NOTICE: GL_VERSION = OpenGL ES 2.0
11:32:28 T:1933888776  NOTICE: GL_SHADING_LANGUAGE_VERSION = OpenGL ES GLSL ES 1.00
11:32:28 T:1933888776  NOTICE: GL_EXTENSIONS = GL_EXT_debug_marker GL_OES_texture_npot GL_OES_compressed_ETC1_RGB8_texture GL_OES_standard_derivatives GL_OES_EGL_image GL_OES_depth24 GL_ARM_rgba8 GL_ARM_mali_shader_binary GL_OES_depth_texture GL_OES_packed_depth_stencil GL_EXT_texture_format_BGRA8888 GL_OES_vertex_half_float GL_EXT_blend_minmax GL_OES_EGL_image_external GL_OES_EGL_sync GL_OES_rgb8_rgba8 GL_EXT_multisampled_render_to_texture GL_EXT_discard_framebuffer GL_OES_get_program_binary GL_ARM_mali_program_binary GL_EXT_shader_texture_lod GL_EXT_robustness GL_OES_depth_texture_cube_map GL_KHR_debug
11:32:28 T:1988809160  NOTICE: ES: Starting UDP Event server on 0.0.0.0:9777
11:32:28 T:1988809160  NOTICE: UDP: Listening on port 9777
11:32:29 T:1977290328   ERROR: Error loading addon settings to special://profile/addon_data/script.module.dudehere.routines/settings.xml
11:32:31 T:1977326496   ERROR: Previous line repeats 9 times.
11:32:31 T:1977326496  NOTICE: URLResolver: Initializing URLResolver version: 3.0.32
11:32:32 T:1977290328  NOTICE: Previous line repeats 1 times.
11:32:32 T:1977290328  NOTICE: DudeHere Common Routines: Setting DHCR API Access log to: /storage/emulated/0/Android/data/com.semperpax.spmc16/files/.spmc/userdata/addon_data/script.module.dudehere.routines/access.log
11:32:32 T:1977326496  NOTICE: Stream All The Sources: Service: Installed Version: 2.0.136
11:32:32 T:1977290328  NOTICE: DudeHere Common Routines: DHCR Service Starting...
11:32:32 T:1977290328  NOTICE: DudeHere Common Routines:  
                                            MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
                                            MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
                                            MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
                                            MMMMMMMMMMMMMMMMM DudeHere - 2016 - http://forums.tvaddons.ag MMMMMMMMMMMMMMMMMM
                                            MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
                                            MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
                                            MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
11:32:32 T:1977290328  NOTICE: DudeHere Common Routines: Version: 0.7.11
11:32:32 T:1977290328  NOTICE: DudeHere Common Routines: Repository installed: False
11:32:32 T:1977290328  NOTICE: DudeHere Common Routines: Transmogrifier installed: False
11:32:32 T:1977290328  NOTICE: DudeHere Common Routines: Walter Sobchak installed: False
11:32:32 T:1977290328  NOTICE: DudeHere Common Routines: Launching Fanart WebInterface on: 127.0.0.1:8630
11:32:32 T:1977326496  NOTICE: Stream All The Sources: Service: starting...
11:32:51 T:2058778824  NOTICE: URLResolver: Initializing URLResolver version: 3.0.32
11:32:52 T:2058778824  NOTICE: Stream All The Sources: Version: |2.0.136| Queries: |{'mode': 'main'}|
11:32:52 T:2058778824  NOTICE: Stream All The Sources: Args: |['plugin://plugin.video.salts/', '1', '']|
11:32:52 T:2058778824 WARNING: CPythonInvoker(2, /storage/emulated/0/Android/data/com.semperpax.spmc16/files/.spmc/addons/plugin.video.salts/default.py): the python script "/storage/emulated/0/Android/data/com.semperpax.spmc16/files/.spmc/addons/plugin.video.salts/default.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon9xbmcaddon5AddonE
11:32:55 T:2059583968  NOTICE: URLResolver: Initializing URLResolver version: 3.0.32
11:32:56 T:2059583968  NOTICE: Stream All The Sources: Version: |2.0.136| Queries: |{'section': 'Movies', 'mode': 'browse'}|
11:32:56 T:2059583968  NOTICE: Stream All The Sources: Args: |['plugin://plugin.video.salts/', '2', '?mode=browse&section=Movies']|
11:32:57 T:2059583968   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'urllib2.HTTPError'>
                                            Error Contents: HTTP Error 403: Forbidden
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/com.semperpax.spmc16/files/.spmc/addons/plugin.video.salts/default.py", line 2751, in <module>
                                                sys.exit(main())
                                              File "/storage/emulated/0/Android/data/com.semperpax.spmc16/files/.spmc/addons/plugin.video.salts/default.py", line 2742, in main
                                                url_dispatcher.dispatch(mode, queries)
                                              File "/storage/emulated/0/Android/data/com.semperpax.spmc16/files/.spmc/addons/script.module.tknorris.shared/lib/url_dispatcher.py", line 100, in dispatch
                                                self.func_registry[mode](*args, **kwargs)
                                              File "/storage/emulated/0/Android/data/com.semperpax.spmc16/files/.spmc/addons/plugin.video.salts/default.py", line 101, in browse_menu
                                                add_section_lists(section)
                                              File "/storage/emulated/0/Android/data/com.semperpax.spmc16/files/.spmc/addons/plugin.video.salts/default.py", line 293, in add_section_lists
                                                add_other_list_item(MODES.BROWSE, section, other_list)
                                              File "/storage/emulated/0/Android/data/com.semperpax.spmc16/files/.spmc/addons/plugin.video.salts/default.py", line 637, in add_other_list_item
                                                header = trakt_api.get_list_header(other_list[1], other_list[0], bool(TOKEN))
                                              File "/storage/emulated/0/Android/data/com.semperpax.spmc16/files/.spmc/addons/plugin.video.salts/salts_lib/trakt_api.py", line 108, in get_list_header
                                                return self.__call_trakt(url, auth=auth)
                                              File "/storage/emulated/0/Android/data/com.semperpax.spmc16/files/.spmc/addons/plugin.video.salts/salts_lib/trakt_api.py", line 470, in __call_trakt
                                                response = urllib2.urlopen(request, timeout=self.timeout)
                                              File "/var/lib/jenkins/jobs/SPMC-Custom-ARM/workspace/tools/depends/xbmc-depends/arm-linux-androideabi-android-17/lib/python2.6/urllib2.py", line 126, in urlopen
                                              File "/var/lib/jenkins/jobs/SPMC-Custom-ARM/workspace/tools/depends/xbmc-depends/arm-linux-androideabi-android-17/lib/python2.6/urllib2.py", line 397, in open
                                              File "/var/lib/jenkins/jobs/SPMC-Custom-ARM/workspace/tools/depends/xbmc-depends/arm-linux-androideabi-android-17/lib/python2.6/urllib2.py", line 510, in http_response
                                              File "/var/lib/jenkins/jobs/SPMC-Custom-ARM/workspace/tools/depends/xbmc-depends/arm-linux-androideabi-android-17/lib/python2.6/urllib2.py", line 435, in error
                                              File "/var/lib/jenkins/jobs/SPMC-Custom-ARM/workspace/tools/depends/xbmc-depends/arm-linux-androideabi-android-17/lib/python2.6/urllib2.py", line 369, in _call_chain
                                              File "/var/lib/jenkins/jobs/SPMC-Custom-ARM/workspace/tools/depends/xbmc-depends/arm-linux-androideabi-android-17/lib/python2.6/urllib2.py", line 518, in http_error_default
                                            HTTPError: HTTP Error 403: Forbidden
                                            -->End of Python script error report<--
11:32:57 T:2059583968 WARNING: CPythonInvoker(3, /storage/emulated/0/Android/data/com.semperpax.spmc16/files/.spmc/addons/plugin.video.salts/default.py): the python script "/storage/emulated/0/Android/data/com.semperpax.spmc16/files/.spmc/addons/plugin.video.salts/default.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon9xbmcaddon5AddonE
11:32:57 T:1933888776   ERROR: static bool XFILE::CDirectory::GetDirectory(const CURL&, CFileItemList&, const XFILE::CDirectory::CHints&, bool) - Error getting plugin://plugin.video.salts/?mode=browse&section=Movies
11:32:57 T:1933888776   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.salts/?mode=browse&section=Movies) failed
11:33:01 T:2067741696  NOTICE: URLResolver: Initializing URLResolver version: 3.0.32
11:33:02 T:2067741696  NOTICE: Stream All The Sources: Version: |2.0.136| Queries: |{'section': 'TV', 'mode': 'browse'}|
11:33:02 T:2067741696  NOTICE: Stream All The Sources: Args: |['plugin://plugin.video.salts/', '3', '?mode=browse&section=TV']|
11:33:03 T:2067741696   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'urllib2.HTTPError'>
                                            Error Contents: HTTP Error 403: Forbidden
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/com.semperpax.spmc16/files/.spmc/addons/plugin.video.salts/default.py", line 2751, in <module>
                                                sys.exit(main())
                                              File "/storage/emulated/0/Android/data/com.semperpax.spmc16/files/.spmc/addons/plugin.video.salts/default.py", line 2742, in main
                                                url_dispatcher.dispatch(mode, queries)
                                              File "/storage/emulated/0/Android/data/com.semperpax.spmc16/files/.spmc/addons/script.module.tknorris.shared/lib/url_dispatcher.py", line 100, in dispatch
                                                self.func_registry[mode](*args, **kwargs)
                                              File "/storage/emulated/0/Android/data/com.semperpax.spmc16/files/.spmc/addons/plugin.video.salts/default.py", line 101, in browse_menu
                                                add_section_lists(section)
                                              File "/storage/emulated/0/Android/data/com.semperpax.spmc16/files/.spmc/addons/plugin.video.salts/default.py", line 293, in add_section_lists
                                                add_other_list_item(MODES.BROWSE, section, other_list)
                                              File "/storage/emulated/0/Android/data/com.semperpax.spmc16/files/.spmc/addons/plugin.video.salts/default.py", line 637, in add_other_list_item
                                                header = trakt_api.get_list_header(other_list[1], other_list[0], bool(TOKEN))
                                              File "/storage/emulated/0/Android/data/com.semperpax.spmc16/files/.spmc/addons/plugin.video.salts/salts_lib/trakt_api.py", line 108, in get_list_header
                                                return self.__call_trakt(url, auth=auth)
                                              File "/storage/emulated/0/Android/data/com.semperpax.spmc16/files/.spmc/addons/plugin.video.salts/salts_lib/trakt_api.py", line 470, in __call_trakt
                                                response = urllib2.urlopen(request, timeout=self.timeout)
                                              File "/var/lib/jenkins/jobs/SPMC-Custom-ARM/workspace/tools/depends/xbmc-depends/arm-linux-androideabi-android-17/lib/python2.6/urllib2.py", line 126, in urlopen
                                              File "/var/lib/jenkins/jobs/SPMC-Custom-ARM/workspace/tools/depends/xbmc-depends/arm-linux-androideabi-android-17/lib/python2.6/urllib2.py", line 397, in open
                                              File "/var/lib/jenkins/jobs/SPMC-Custom-ARM/workspace/tools/depends/xbmc-depends/arm-linux-androideabi-android-17/lib/python2.6/urllib2.py", line 510, in http_response
                                              File "/var/lib/jenkins/jobs/SPMC-Custom-ARM/workspace/tools/depends/xbmc-depends/arm-linux-androideabi-android-17/lib/python2.6/urllib2.py", line 435, in error
                                              File "/var/lib/jenkins/jobs/SPMC-Custom-ARM/workspace/tools/depends/xbmc-depends/arm-linux-androideabi-android-17/lib/python2.6/urllib2.py", line 369, in _call_chain
                                              File "/var/lib/jenkins/jobs/SPMC-Custom-ARM/workspace/tools/depends/xbmc-depends/arm-linux-androideabi-android-17/lib/python2.6/urllib2.py", line 518, in http_error_default
                                            HTTPError: HTTP Error 403: Forbidden
                                            -->End of Python script error report<--
11:33:03 T:2067741696 WARNING: CPythonInvoker(4, /storage/emulated/0/Android/data/com.semperpax.spmc16/files/.spmc/addons/plugin.video.salts/default.py): the python script "/storage/emulated/0/Android/data/com.semperpax.spmc16/files/.spmc/addons/plugin.video.salts/default.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon9xbmcaddon5AddonE
11:33:03 T:1933888776   ERROR: static bool XFILE::CDirectory::GetDirectory(const CURL&, CFileItemList&, const XFILE::CDirectory::CHints&, bool) - Error getting plugin://plugin.video.salts/?mode=browse&section=TV
11:33:03 T:1933888776   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.salts/?mode=browse&section=TV) failed

**Comment by brmnh** [comment]
Hi Sir,can you fix the problem?Thanks

**Comment by tknorris** [comment]
I'm not involved with SALTS any longer, you'll have to go else where for help. I have no information on where.

**Comment by brmnh** [comment]
Sir,is k313vra on github?

**Comment by tknorris** [comment]
again, I have no information for you. Please stop asking.
