### ISSUE TITLE
Please could you add uptobox.com and uptostream.com.

### ISSUE THREAD

**Issue by Sanjjay** [tknorris/script.module.urlresolver#37]
Please could you add Uptobox and Uptostream in URL resolver.

uptobox.com python script
https://github.com/lambda81/lambda-addons/blob/master/plugin.video.genesis/resources/lib/resolvers/uptobox.py

uptostream.com python script
https://github.com/LordVenom/venom-xbmc-addons/blob/master/plugin.video.vstream/resources/hosters/uptostream.py

Hope to hear from you

Many thanks!

**Comment by tknorris** [comment]
smoked just submitted resolvers for these hosts. I'll include them in the next tva release.

**Comment by Sanjjay** [comment]
Many Thanks!!!
