### ISSUE TITLE
Hi sir these hosts cannot be resolved right now

### ISSUE THREAD

**Issue by brmnh** [tknorris/script.module.urlresolver#4]
uploadc.com(still cannot),  play.to,   noslocker.com,  cloudzilla.to,   zalaa.com,  movdivx.com(still cannot),

**Comment by tknorris** [comment]
did you install uploadc and movdivx from my my github repo?

**Comment by tknorris** [comment]
the zalaa site currently appears broken, I can't get it to work in my browser.
noslocker and cloudzilla don't currently have resolvers
I don't recognize play.to. Did you mean played.to?

**Comment by tknorris** [comment]
noslocker and cloudzilla look doable. I'll add those tomorrow.

**Comment by brmnh** [comment]
Sir,I just download and install you script.module.urlresolver from this link:https://github.com/tknorris/script.module.urlresolver/tree/f50a13cbe958d620577d0ee8133e1a0d1c19fdbc

**Comment by brmnh** [comment]
I download your github repo from this link:https://github.com/tknorris/tknorris-beta-repo/tree/cafafe505337caf7faa25dab1860b8f14327e433
But when I install it into kodi it says addon doesnot have the correct stucture,I cannot install it.

**Comment by tknorris** [comment]
it's best to just wait until a urlresovler update is pushed if you don't know how to install from github.

**Comment by brmnh** [comment]
and the host is played.to,I try once more and it works,I made a mistake.

**Comment by brmnh** [comment]
sir how to install your repo when it says that doesnot have correct structure?I know how to install urlreolver and 1channe and salt,I just donot know how to install your repo.

**Comment by tknorris** [comment]
I pushed a fix for uploadc. I retested movdivx and it's working. Send me an example of a movdivx link that you have that doesn't work if you have one.

**Comment by tknorris** [comment]
don't worry about installing my beta repo. That won't help you with urlresolver.

**Comment by brmnh** [comment]
Sir you can try this film on 1channel,it has uploadc host link: the luck of the irish(1948)

**Comment by brmnh** [comment]
about  movdivx.com youcan try this film: A Date with Judy (1948)

**Comment by brmnh** [comment]
Sir when you make noslocker and cloudzilla resolvers can you also make a resolver for tubemotion.com?

**Comment by brmnh** [comment]
I just download your newest urlresolver script,uploadc.com resolver works.

**Comment by tknorris** [comment]
movdivx fixed. tubemotion looks more like a scraper site than a hoster. I'll look at it for inclusion in SALTS.

**Comment by brmnh** [comment]
Thank you sir.

**Comment by tknorris** [comment]
cloudzilla added and nosvdieo extended to support noslocker

**Comment by brmnh** [comment]
Thanks

**Comment by brmnh** [comment]
Sir,these hosts seems also donnot have resolver:  vid.ag    vidup.me
