### ISSUE TITLE
usersfiles.com and mediaplaybox.com

### ISSUE THREAD

**Issue by Sanjjay** [tknorris/script.module.urlresolver#41]
Please could you add mediaplaybox.com to UrlResolver aswell.

http://apple-tv2-xbmc.googlecode.com/svn/trunk/addons/script.module.turtlex/lib/snapvideo/MediaPlayBox.py

I couldn't find a python script for usersfiles.com would appreciate it if you could make a script for it.

Many thanks!

**Comment by tknorris** [comment]
mediaplaybox added, I don't see any links to userfiles.com to test againt.

**Comment by Sanjjay** [comment]
Thank you for adding mediaplaybox.

Would the link below help to test and add usersfiles.com to urlresolver.

http://usersfiles.com/ware8251m1sa

**Comment by tknorris** [comment]
Yep, resolver added.

**Comment by Sanjjay** [comment]
Many Thanks!!!
