### ISSUE TITLE
Add "lizshare.com" & "noslocker.com" resolver

### ISSUE THREAD

**Issue by itzikg** [tknorris/script.module.urlresolver#49]
Hello,

Is it possible to add "lizshare.com" & "noslocker.com" urlresolver support.

Thanks

**Comment by tknorris** [comment]
I can take a look at them.

**Comment by tknorris** [comment]
noslocker has encoded their pages to the point it's not worth the effort to try to fix it.
Do you have a lizshare url I can use to test?

**Comment by itzikg** [comment]
Hey you are responsible for resolver or Eldorados?
Is not available for a long time and does not answer
What's up with updates there?

**Comment by tknorris** [comment]
There is no such thing as "responsible" when it comes to this stuff. People contribute as they can/have time. Eldorado owns this addon and I contribute when I have time. I also release a special version through TVA's repositories that is updated more frequently than the one in the official repository.

Did you read my last comment in terms of updates?

**Comment by tknorris** [comment]
If you don't have a lizshare link I can test, I will close this issue.
