### ISSUE TITLE
docs.google.com and kingfiles.net

### ISSUE THREAD

**Issue by Sanjjay** [tknorris/script.module.urlresolver#50]
Please could you add resolvers below.

docs.google.com link https://docs.google.com/file/d/0Bybocos_-5kbU3I5LVA3Y290X3M/view?pli=1

kingfiles.net link http://kingfiles.net/bo0kpasiyplg

Many thanks.

Sanjay

**Comment by tknorris** [comment]
kingfiles will be in the next TVA build of urlresolver. I leave it to someone else to do google docs.

**Comment by Sanjjay** [comment]
How do I go about getting someone else to do google docs.

**Comment by tknorris** [comment]
@smokdpi you have any interest in updating the google docs resolver? I have some code in salts that might help: https://github.com/tknorris/salts/blob/master/scrapers/clickplay_scraper.py#L98

**Comment by Sanjjay** [comment]
Thank you for asking smokdpi.

**Comment by Sanjjay** [comment]
google searching brought these up, thought I'd post it here if it helps in anyway.

https://github.com/daniel-lundin/dreamfilm-xbmc/blob/6c55cbb25369b2c8f76aa3e51b479942718e48be/resolvers.py

https://github.com/ddurdle/GDrive-for-KODI/blob/master/resources/lib/gdrive.py
