### ISSUE TITLE
Hi Sir,these resolvers seem broken

### ISSUE THREAD

**Issue by brmnh** [tknorris/script.module.urlresolver#51]
veehd.com        filenuke.com       thefile.me      sharesix.com       sharerepo.com         openload.co        allmyvideos.net        zalaa.com      180upload.com       cloudy.sx        cloudy.ec      cloudy.eu        cloudy.ch       cloudy.com      cloudyvideos.com       cloudzilla.to       neodrive.co      daclips.in        daclips.com        divxstage.eu       divxstage.net       divxstage.to       cloudtime.to      filehoot.com       filepup.net         flashx.tv       googlevideo.com        picasaweb.google.com         gorillavid.in      gorillavid.com       grifthost.com       hugefiles.net     letwatch.us       mightyupload.com       movdivx.com                        movpod.net        movpod.in       movshare.net        mrfile.me        nosvideo.com        noslocker.com     novamov.com        nowvideo.eu        nowvideo.ch    nowvideo.sx         nowvideo.co       nowvideo.li      openload.io      putlocker.com       filedrive.com      firedrive.com        realvid.net        stagevu.com       streamcloud.eu       thevideo.me       uploadc.com        vid.ag       vidbull.com        videomega.tv       video.tt       videoweed.es       vidspot.net        vidto.me      vidup.org       vidup.me      vidxden.com      vidxden.to      divxden.com       vidbux.com    vidbux.to    youwatch.org

**Comment by tknorris** [comment]
Thanks. I'll look at them when I have time.

**Comment by brmnh** [comment]
Thanks Sir.

**Comment by tknorris** [comment]
Thanks for all the reports. We've made lots of changes to resolvers. It would probably be best to wait to do further testing until after 2.10.11 comes out. I'm going to close this issue for now. Open a new one once you've tested on 2.10.11
