### ISSUE TITLE
Hi Sir,these resolvers seem broken

### ISSUE THREAD

**Issue by brmnh** [tknorris/script.module.urlresolver#57]
streamin.to        stagevu.com           filenuke.com          sharerepo.com          sharesix.com

**Comment by smokdpi** [comment]
streamin seems to be working
stagevu seems to be down currently, no indication of how long this will last
sharesix resolvers needs an update
filenuke/sharerepo returning results, failed open on playback(url appears correct). Does not appear to be resolver related (web video currently taking > 120sec to initiate during testing) will check again later.

**Comment by brmnh** [comment]
Thanks Sir.

**Comment by tknorris** [comment]
I checked sharesix and it returned the correct url but it timed out. The site timed out in the browser too, so I think it's just the host with issues.
