### ISSUE TITLE
Hi Sir,the scraper alluc.com issue still not solved

### ISSUE THREAD

**Issue by brmnh** [tknorris/script.module.urlresolver#59]
it still reminds time out.

**Comment by tknorris** [comment]
Change the base url to http://www.alluc.ee and it'll work

**Comment by brmnh** [comment]
Hi sir,how to change?

**Comment by brmnh** [comment]
I download you newest salts addon,it still doesnot work.

**Comment by brmnh** [comment]
You newest salts addon should have made that change.

**Comment by tknorris** [comment]
Addon Settings->Scrapers1->Alluc.com settings

**Comment by brmnh** [comment]
oh,I add alluc username and password,and it works.Thanks Sir.
