### ISSUE TITLE
Hi Sir,the resolver streamcloud.eu seems broken

### ISSUE THREAD

**Issue by brmnh** [tknorris/script.module.urlresolver#6]
Sir,I here have an kodi addon called plugin.video.115-0.0.10.zip. You can download this addon at: http://pan.baidu.com/s/1i3rLt3n   It is an addon about this website: http://www.115.com/?lang=en.It is a downloader profile. Can you add some search engines for this addon?For example btdigg.org and torrentZ.eu? Just like what this kodi addon plugin.video.xunleicloud-master.zip did.This addon is about the downloader thunder.exe.  You can download this addon at: http://pan.baidu.com/s/1sjkd3jB

**Comment by brmnh** [comment]
and sir,I here have an addon called plugin.video.115-0.0.10.zip.it is an addon about this website: http://www.115.com/?lang=en.Can you add some search engines for this addon?For example btdigg.org and torrentZ.eu?

**Comment by brmnh** [comment]
When you install these two addons,please change system/setting/appearance/skin/fonts to arial based,because these two addons are in chinese.

**Comment by brmnh** [comment]
these two addon are both about downloading(http,magnet,ed2k),cloud storage,streaming.

**Comment by tknorris** [comment]
Sorry, I don't do torrrent addons.
