### ISSUE TITLE
Hi Sir,the resolver veehd.com seems have some problem

### ISSUE THREAD

**Issue by brmnh** [tknorris/script.module.urlresolver#60]
I tried many veehd link movies in kodi,almost half of them report "link resolve failed".There are not so many dead veehd links before.Sir,can you make some fix on the resolver?Thanks very much.

**Comment by brmnh** [comment]
Sir,when I visit the "link resolve failed" veehd link in the browser,it reminds "The server this video is on is undergoing maintenance. Expect a high error rate.".I donot know if this is why the veehd link cannot be played in kodi.

**Comment by tknorris** [comment]
It appears to be hte case because I tested another video and it worked fine.
