### ISSUE TITLE
Hi Sir,when I use your update I met some problem

### ISSUE THREAD

**Issue by brmnh** [tknorris/script.module.urlresolver#66]
In your resently SALT and urlresolver update,I found no alluc scraper and veehd resolver username and password input section.Without username and password input,alluc and veehd will not work.Sir,can you make some changes in your new update?Thanks very much.

**Comment by brmnh** [comment]
And another question,Sir,when I use the install addon from zips section,I click on the SMB section,it appears workgroup.When I click on workgroup,it appears 'invalid argument'.Sir can you fix this problem?

**Comment by tknorris** [comment]
I'm sorry, what do you mean by SMB? and workgroup? Where are you clicking?

**Comment by tknorris** [comment]
Also, I still see uid/password sections for both things. Are you sure you are looking in the right place? Alluc is in scrapers in SALTS settings and VeeHD is in URLResolver settings.

**Comment by brmnh** [comment]
Sorry Sir,In the first question I made a mistake,there are sections for both alluc and veehd.

**Comment by brmnh** [comment]
I run the kodi on my android tv.In the second,when I click system/addon/install from zip file,in the right screen it appears one section named 'windows network(SMB)',when I click it,it appers 'workgroup',when I click workgroup,it shows 'invalid argument',it should have showed my computer's name.Now I cannot link kodi on android tv with computer.

**Comment by tknorris** [comment]
That really has nothing to do w/ the addon. That's standard kodi functionality, I can't help with that.
