### ISSUE TITLE
urlresolver improvement

### ISSUE THREAD

**Issue by sraedler** [tknorris/script.module.urlresolver#67]
Hey, your project is really great and useful, but I would like to add a feature, which would improve it for many users!

Everybody knows, how boring it is to klick links which are not working. The solution could be to add a function which checks the online state of the video.

The checking whether a page is online or not could be done with a regex, because every page has a "File not found" Text on the page if it is offline.

See for example here: [Streamcloud](http://streamcloud.eu/7vctyii5ipwg/LA_CRASH_2012.avi.html)

What do you think about this feature?

**Comment by tknorris** [comment]
If you'd like to submit a PR for it, I'd be happy to review it for consideration. You'll find it's not as simple as it sounds.

**Comment by sraedler** [comment]
Ok, than I will try it the next days!

Btw. Is there a roadmap for the next release?

**Comment by tknorris** [comment]
It will be released tomorrow as 3.0

**Comment by sraedler** [comment]
Ok, I tried some stuff...

But than I saw this is not needed, because you can check it this way:

`if type(urlresolver.resolve(jHosterEntry[3])) is unicode:`

You could provide a function which returns it, but it's not needed.
