### ISSUE TITLE
NowVideo e NowDownload

### ISSUE THREAD

**Issue by Kolifanes** [tknorris/script.module.urlresolver#77]
URLResolver is not able to decrypt the link of this two host. Normal behavior? Need Real-Debrid?
Thanks

**Comment by tknorris** [comment]
Resolvers break all the time. You'll just have to pick different sources until someone gets around to fixing it.

**Comment by Kolifanes** [comment]
Found the issue, NowVideo and NowDownload change the domain to .ec
This is the problem

**Comment by tknorris** [comment]
Thanks we'll add that in the next release.

**Comment by tknorris** [comment]
code added, will be in 3.0.6
