### ISSUE TITLE
YouTube-Resolver

### ISSUE THREAD

**Issue by Viper2k4** [tknorris/script.module.urlresolver#80]
The actual YouTube-Resolver only cover a few cases. I found a very good (and often updatet) Regex to cover the most possible cases:

http://stackoverflow.com/questions/5830387/how-to-find-all-youtube-video-ids-in-a-string-using-a-regex/5831191#5831191

Maybe this help a bit

**Comment by tknorris** [comment]
Thanks, I'll take a look at it and if it verifies, I'll switch it out for the one in the resolver

**Comment by tknorris** [comment]
Added [here](https://github.com/tknorris/script.module.urlresolver/commit/1a7717156e198663f5be3a1f924e83e6332fa89f). It'll be in the next release
