### ISSUE TITLE
Hi Sir,the resolver movpod.in seems broken

### ISSUE THREAD

**Issue by brmnh** [tknorris/script.module.urlresolver#9]
some videos can be played,some cannot.

**Comment by tknorris** [comment]
Did you verify the ones that can not actually work in the browser?

**Comment by brmnh** [comment]
I tried this one:http://www.primewire.ag/watch-2744522-Bullet-online-free. It can be played in the browser,but cannot be played in xbmc.

**Comment by brmnh** [comment]
resolver daclips.in has the same problem.The same video:http://www.primewire.ag/watch-2744522-Bullet-online-free can be played in browser,but cannot be played in xbmc.

**Comment by tknorris** [comment]
The problem is it's timing out. Kodi only allows 30 seconds for a stream to start and movpod and daclips frequently require longer than that.

**Comment by brmnh** [comment]
when it meams time out,it seems that a sign "working" will appear in bottom right corner for some time.

**Comment by brmnh** [comment]
"working" just didnot appear.

**Comment by brmnh** [comment]
it seems there are three conditions:one,"working" appears some time,and video can be played.two,"working" appears some time,but video cannot be played.Three,"working" just donot appear.

**Comment by tknorris** [comment]
It depends on when the timeout happens. If it happens before we pass the video back to Kodi, then working won't show, if the timeout happens afterwards, then it will show. Regardless, they are both timeouts.

**Comment by brmnh** [comment]
if it is condition two,when I change player to mx player pro,the video can be played finally.if it is condition three,when i change player the video still cannot be played.

**Comment by tknorris** [comment]
I tested that video on both sites and movpod takes nearly 1.5 minutes to start the video and daclips takes nearly 45 seconds. Both of these will time out in Kodi. I verified that both videos are getting passed back to Kodi correctly. There's nothing to be fixed here that I can see.

**Comment by brmnh** [comment]
Since both are time out,can we change condition three to condition two?

**Comment by tknorris** [comment]
No, the timeouts are set so that playback start doesn't take forever, if each request to the hoster take 45 seconds to a minute, then it could take as long as 3 minutes to even start the working dialog. If you haev auto-play turned on, that would be a real pain.

**Comment by brmnh** [comment]
it seems only way to see the video is to change resolver

**Comment by brmnh** [comment]
Thanks Sir.
